/* hui/bin/joined.site.js */
var hui={browser:{},KEY_BACKSPACE:8,KEY_TAB:9,KEY_RETURN:13,KEY_ESC:27,KEY_LEFT:37,KEY_UP:38,KEY_RIGHT:39,KEY_DOWN:40,KEY_DELETE:46,KEY_HOME:36,KEY_END:35,KEY_PAGEUP:33,KEY_PAGEDOWN:34,KEY_INSERT:45}
if(hui.browser.opera=/opera/i.test(navigator.userAgent),hui.browser.msie=!hui.browser.opera&&/MSIE/.test(navigator.userAgent)||/Trident/.test(navigator.userAgent),hui.browser.msie6=-1!==navigator.userAgent.indexOf("MSIE 6"),hui.browser.msie7=-1!==navigator.userAgent.indexOf("MSIE 7"),hui.browser.msie8=-1!==navigator.userAgent.indexOf("MSIE 8"),hui.browser.msie9=-1!==navigator.userAgent.indexOf("MSIE 9"),hui.browser.msie9compat=hui.browser.msie7&&-1!==navigator.userAgent.indexOf("Trident/5.0"),hui.browser.msie10=-1!==navigator.userAgent.indexOf("MSIE 10"),hui.browser.msie11=-1!==navigator.userAgent.indexOf("Trident/7.0"),hui.browser.webkit=-1!==navigator.userAgent.indexOf("WebKit"),hui.browser.safari=-1!==navigator.userAgent.indexOf("Safari"),hui.browser.chrome=-1!==navigator.userAgent.indexOf("Chrome"),hui.browser.webkitVersion=null,hui.browser.gecko=!hui.browser.webkit&&!hui.browser.msie&&-1!==navigator.userAgent.indexOf("Gecko"),hui.browser.chrome=-1!==navigator.userAgent.indexOf("Chrome"),hui.browser.ipad=hui.browser.webkit&&-1!==navigator.userAgent.indexOf("iPad"),hui.browser.windows=-1!==navigator.userAgent.indexOf("Windows"),hui.browser.opacity=!hui.browser.msie6&&!hui.browser.msie7&&!hui.browser.msie8,hui.browser.mediaQueries=hui.browser.opacity,hui.browser.animation=!(hui.browser.msie6||hui.browser.msie7||hui.browser.msie8||hui.browser.msie9),hui.browser.wordbreak=!hui.browser.msie6&&!hui.browser.msie7&&!hui.browser.msie8,hui.browser.touch="ontouchstart"in window||"onmsgesturechange"in window&&window.navigator.maxTouchPoints?!0:!1,function(){var e=/Safari\/([\d.]+)/.exec(navigator.userAgent)
e&&(hui.browser.webkitVersion=parseFloat(e[1]))}(),hui.log=function(e){try{1==arguments.length?console.log(e):2==arguments.length?console.log(arguments[0],arguments[1]):console.log(arguments)}catch(t){}},hui.defer=function(e,t){t&&(e=e.bind(t)),window.setTimeout(e)},hui.override=function(e,t){if(t)for(var i in t)e[i]=t[i]
return e},hui.each=function(e,t){var i
if(hui.isArray(e))for(i=0;i<e.length;i++)t(e[i],i)
else if(e instanceof NodeList)for(i=0;i<e.length;i++)t(e.item(i),i)
else for(var n in e)t(n,e[n])},hui.when=function(e,t){return e?t:""},hui.intOrString=function(e){if(hui.isDefined(e)){var t=/[0-9]+/.exec(e)
if(null!==t&&t[0]==e&&parseInt(e,10)==e)return parseInt(e,10)}return e},hui.between=function(e,t,i){var n=Math.min(i,Math.max(e,t))
return isNaN(n)?e:n},hui.isBlank=function(e){return null===e||"undefined"==typeof e||""===e?!0:"string"==typeof e&&0===hui.string.trim(e).length},hui.isDefined=function(e){return null!==e&&"undefined"!=typeof e},hui.isString=function(e){return"string"==typeof e},hui.isArray=function(e){return null===e||void 0===e?!1:e.constructor==Array?!0:"[object Array]"===Object.prototype.toString.call(e)},hui.string={startsWith:function(e,t){return"string"!=typeof e||"string"!=typeof t?!1:e.match("^"+t)==t},endsWith:function(e,t){return"string"!=typeof e||"string"!=typeof t?!1:e.match(t+"$")==t},camelize:function(e){if(-1==e.indexOf("-"))return e
for(var t=e.split("-"),i=0===e.indexOf("-")?t[0].charAt(0).toUpperCase()+t[0].substring(1):t[0],n=1,o=t.length;o>n;n++){var s=t[n]
i+=s.charAt(0).toUpperCase()+s.substring(1)}return i},trim:function(e){return null===e||void 0===e?"":("string"!=typeof e&&(e=String(e)),e.replace(/^[\s\x0b\xa0\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u200b\u2028\u2029\u3000]+|[\s\x0b\xa0\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u200b\u2028\u2029\u3000]+$/g,""))},wrap:function(e){return null===e||void 0===e?"":e.split("").join("​")},shorten:function(e,t){return hui.isDefined(e)?e.length>t?e.substring(0,t-3)+"...":e:""},escapeHTML:function(e){return null===e||void 0===e?"":hui.build("div",{text:e}).innerHTML},escape:function(e){return hui.isDefined(e)?e.replace(/&/g,"&amp;").replace(/>/g,"&gt;").replace(/</g,"&lt;").replace(/"/g,"&quot;"):""},fromJSON:function(e){try{return JSON.parse(e)}catch(t){return hui.log(t),null}},toJSON:function(e){return JSON.stringify(e)}},hui.array={add:function(e,t){if(t.constructor==Array)for(var i=0;i<t.length;i++)hui.array.contains(e,t[i])||e.push(t)
else hui.array.contains(e,t)||e.push(t)},contains:function(e,t){return-1!==hui.array.indexOf(e,t)},flip:function(e,t){hui.array.contains(e,t)?hui.array.remove(e,t):e.push(t)},remove:function(e,t){for(var i=e.length-1;i>=0;i--)e[i]==t&&e.splice(i,1)},indexOf:function(e,t){for(var i=0;i<e.length;i++)if(e[i]===t)return i
return-1},toIntegers:function(e){for(var t=e.split(","),i=t.length-1;i>=0;i--)t[i]=parseInt(t[i],10)
return t}},hui.dom={isElement:function(e,t){return 1==e.nodeType&&(void 0===t?!0:e.nodeName.toLowerCase()==t)},isDefinedText:function(e){return 3==e.nodeType&&e.nodeValue.length>0},addText:function(e,t){e.appendChild(document.createTextNode(t))},firstChild:function(e){for(var t=e.childNodes,i=0;i<t.length;i++)if(1==t[i].nodeType)return t[i]
return null},parseToNode:function(e){var t=hui.build("div",{html:e})
return hui.get.firstChild(t,"table")},clear:function(e){for(var t=e.childNodes,i=t.length-1;i>=0;i--)t[i].parentNode.removeChild(t[i])},remove:function(e){e.parentNode&&e.parentNode.removeChild(e)},replaceNode:function(e,t){t.parentNode&&t.parentNode.removeChild(t),e.parentNode.insertBefore(t,e),e.parentNode.removeChild(e)},changeTag:function(e,t){for(var i=hui.build(t);e.firstChild;)i.appendChild(e.firstChild)
for(var n=e.attributes.length-1;n>=0;--n)i.attributes.setNamedItem(e.attributes[n].cloneNode())
return e.parentNode.insertBefore(i,e),e.parentNode.removeChild(e),i},insertBefore:function(e,t){e.parentNode.insertBefore(t,e)},insertAfter:function(e,t){var i=e.nextSibling
i?i.parentNode.insertBefore(t,i):e.parentNode.appendChild(t)},replaceHTML:function(e,t){e=hui.get(e),e.innerHTML=t},runScripts:function(node){if(hui.dom.isElement(node))if(hui.dom.isElement(node,"script"))eval(node.innerHTML)
else for(var scripts=node.getElementsByTagName("script"),i=0;i<scripts.length;i++)eval(scripts[i].innerHTML)},setText:function(e,t){(void 0===t||null===t)&&(t="")
for(var i=e.childNodes,n=!1,o=i.length-1;o>=0;o--)n||3!==i[o].nodeType?e.removeChild(i[o]):(i[o].nodeValue=t,n=!0)
n||hui.dom.addText(e,t)},getText:function(e){for(var t="",i=e.childNodes,n=0;n<i.length;n++)3===i[n].nodeType&&null!==i[n].nodeValue?t+=i[n].nodeValue:1==i[n].nodeType&&(t+=hui.dom.getText(i[n]))
return t},isVisible:function(e){for(;e;){if(e.style&&("none"===hui.style.get(e,"display")||"hidden"===hui.style.get(e,"visibility")))return!1
e=e.parentNode}return!0},isDescendantOrSelf:function(e,t){for(;e;){if(e==t)return!0
e=e.parentNode}return!1}},hui.form={getValues:function(e){for(var t={},i=e.getElementsByTagName("input"),n=0;n<i.length;n++)hui.isDefined(i[n].name)&&(t[i[n].name]=i[n].value)
return t}},hui.get=function(e){return"string"==typeof e?document.getElementById(e):e},hui.get.children=function(e){for(var t=[],i=e.childNodes,n=0;n<i.length;n++)hui.dom.isElement(i[n])&&t.push(i[n])
return t},hui.get.ancestors=function(e){for(var t=[],i=e.parentNode;i;)t[t.length]=i,i=i.parentNode
return t},hui.get.firstAncestorByClass=function(e,t){for(;e;){if(hui.cls.has(e,t))return e
e=e.parentNode}return null},hui.get.next=function(e){if(!e)return null
if(e.nextElementSibling)return e.nextElementSibling
if(!e.nextSibling)return null
for(var t=e.nextSibling;t&&1!=t.nodeType;)t=t.nextSibling
return t&&1==t.nodeType?t:null},hui.get.previous=function(e){if(!e)return null
if(e.previousElementSibling)return e.previousElementSibling
if(!e.previousSibling)return null
for(var t=e.previousSibling;t&&1!=t.nodeType;)t=t.previousSibling
return t&&1==t.nodeType?t:null},hui.get.before=function(e){var t=[]
if(e)for(var i=e.parentNode.childNodes,n=0;n<i.length&&i[n]!=e;n++)1===i[n].nodeType&&t.push(i[n])
return t},hui.get.after=function(e){for(var t=[],i=hui.get.next(e);i;)t.push(i),i=hui.get.next(i)
return t},hui.get.firstByClass=function(e,t,i){if(e=hui.get(e)||document.body,e.querySelector)return e.querySelector((i?i+".":".")+t)
for(var n=e.getElementsByTagName(i||"*"),o=0;o<n.length;o++)if(hui.cls.has(n[o],t))return n[o]
return null},hui.get.byClass=function(e,t,i){e=hui.get(e)||document.body
var n
if(e.querySelectorAll){var o=e.querySelectorAll((i?i+".":".")+t),s=[]
for(n=0,ll=o.length;n!=ll;s.push(o[n++]));return s}var a=e.getElementsByTagName(i||"*"),r=[]
for(n=0;n<a.length;n++)hui.cls.has(a[n],t)&&(r[r.length]=a[n])
return r},hui.get.byTag=function(e,t){for(var i=e.getElementsByTagName(t),n=[],o=0,s=i.length;o!=s;n.push(i[o++]));return n},hui.get.byId=function(e,t){for(var i=e.childNodes,n=i.length-1;n>=0;n--){if(1===i[n].nodeType&&i[n].getAttribute("id")===t)return i[n]
var o=hui.get.byId(i[n],t)
if(o)return o}return null},hui.get.firstParentByTag=function(e,t){for(var i=e;i;){if(i.tagName&&i.tagName.toLowerCase()==t)return i
i=i.parentNode}return null},hui.get.firstParentByClass=function(e){for(var t=e;t;){if(hui.cls.has(t))return t
t=t.parentNode}return null},hui.get.firstByTag=function(e,t){if(e=hui.get(e)||document.body,e.querySelector&&"*"!==t)return e.querySelector(t)
var i=e.getElementsByTagName(t)
return i[0]},hui.get.firstChild=hui.dom.firstChild,hui.find=function(e,t){return(t||document).querySelector(e)},hui.collect=function(e,t){for(key in e)e[key]=hui.get.firstByClass(t,e[key])},hui.build=function(e,t,i){i=i||document
var n=i.createElement(e)
if(t)for(var o in t)"text"==o?n.appendChild(i.createTextNode(t.text)):"html"==o?n.innerHTML=t.html:"parent"==o&&hui.isDefined(t.parent)?t.parent.appendChild(n):"parentFirst"==o?0===t.parentFirst.childNodes.length?t.parentFirst.appendChild(n):t.parentFirst.insertBefore(n,t.parentFirst.childNodes[0]):"before"==o?t.before.parentNode.insertBefore(n,t.before):"className"==o?n.className=t.className:"class"==o?n.className=t["class"]:"style"==o&&"object"==typeof t[o]?hui.style.set(n,t[o]):"style"==o&&(hui.browser.msie7||hui.browser.msie6)?n.style.setAttribute("cssText",t[o]):hui.isDefined(t[o])&&n.setAttribute(o,t[o])
return n},hui.position={getTop:function(e){if(e=hui.get(e)){for(var t=e.offsetTop,i=e.offsetParent;null!==i;)t+=i.offsetTop,i=i.offsetParent
return t}return 0},getLeft:function(e){if(e=hui.get(e)){for(var t=e.offsetLeft,i=e.offsetParent;null!==i;)t+=i.offsetLeft,i=i.offsetParent
return t}return 0},get:function(e){return{left:hui.position.getLeft(e),top:hui.position.getTop(e)}},getScrollOffset:function(e){e=hui.get(e)
var t=0,i=0
do if(t+=e.scrollTop||0,i+=e.scrollLeft||0,e=e.parentNode,"HTML"===e.tagName)break
while(e)
return{top:t,left:i}},place:function(e){var t=0,i=0,n=hui.get(e.source.element),o=hui.get(e.target.element),s={left:hui.position.getLeft(o),top:hui.position.getTop(o)}
if(t=s.left+o.clientWidth*(e.target.horizontal||0),i=s.top+o.clientHeight*(e.target.vertical||0),t-=n.clientWidth*(e.source.horizontal||0),i-=n.clientHeight*(e.source.vertical||0),e.top&&(i+=e.top),e.left&&(t+=e.left),e.insideViewPort){var a=hui.window.getViewWidth()
t+n.clientWidth>a&&(t=a-n.clientWidth-(e.viewPartMargin||0)),0>t&&(t=0),0>i&&(i=0)
var r=(hui.window.getViewHeight(),hui.window.getScrollTop()+hui.window.getViewHeight()-n.clientHeight),u=hui.window.getScrollTop()
i=Math.max(Math.min(i,r),u)}n.style.top=Math.round(i)+"px",n.style.left=Math.round(t)+"px"},getRemainingHeight:function(e){for(var t=e.parentNode.clientHeight,i=e.parentNode.childNodes,n=0;n<i.length;n++){var o=i[n]
o!==e&&hui.dom.isElement(i[n])&&"absolute"!=hui.style.get(o,"position")&&(t-=o.offsetHeight)}return t}},hui.window={getScrollTop:function(){return window.pageYOffset?window.pageYOffset:document.documentElement&&document.documentElement.scrollTop?document.documentElement.scrollTop:document.body?document.body.scrollTop:0},getScrollLeft:function(){return window.pageYOffset?window.pageXOffset:document.documentElement&&document.documentElement.scrollTop?document.documentElement.scrollLeft:document.body?document.body.scrollLeft:0},scrollTo:function(e){e=hui.override({duration:0,top:0},e)
var t=e.element,i=hui.position.get(t),n=hui.window.getScrollTop(),o=hui.window.getViewHeight(),s=n+o
if(n<i.top+t.clientHeight||i.top<s){var a=i.top-Math.round((o-t.clientHeight)/2)
a-=e.top/2,a=Math.max(0,a)
var r,u=(new Date).getTime()
r=function(){var t=((new Date).getTime()-u)/e.duration
t>1&&(t=1),window.scrollTo(0,n+Math.round((a-n)*hui.ease.fastSlow(t))),1>t&&window.setTimeout(r)},r()}},getViewHeight:function(){return window.innerHeight?window.innerHeight:document.documentElement&&document.documentElement.clientHeight?document.documentElement.clientHeight:document.body?document.body.clientHeight:void 0},getViewWidth:function(){return window.innerWidth?window.innerWidth:document.documentElement&&document.documentElement.clientWidth?document.documentElement.clientWidth:document.body?document.body.clientWidth:void 0}},hui.cls={has:function(e,t){if(e=hui.get(e),!e||!e.className)return!1
if(e.hasClassName)return e.hasClassName(t)
if(e.className==t)return!0
for(var i=e.className.split(/\s+/),n=0;n<i.length;n++)if(i[n]==t)return!0
return!1},add:function(e,t){e=hui.get(e),e&&(e.addClassName&&e.addClassName(t),hui.cls.remove(e,t),e.className+=" "+t)},remove:function(e,t){if(e=hui.get(e),e&&e.className){if(e.removeClassName&&e.removeClassName(t),e.className==t)return void(e.className="")
for(var i="",n=e.className.split(/\s+/),o=0;o<n.length;o++)n[o]!=t&&(o>0&&(i+=" "),i+=n[o])
e.className=i}},toggle:function(e,t){hui.cls.has(e,t)?hui.cls.remove(e,t):hui.cls.add(e,t)},set:function(e,t,i){i?hui.cls.add(e,t):hui.cls.remove(e,t)}},hui.listen=function(e,t,i,n){e=hui.get(e),e&&(document.addEventListener?e.addEventListener(t,i,n?!0:!1):e.attachEvent("on"+t,i))},hui.listenOnce=function(e,t,i){var n=null
n=function(o){hui.unListen(e,t,n),i(o)},hui.listen(e,t,n)},hui.unListen=function(e,t,i,n){e=hui.get(e),document.removeEventListener?e.removeEventListener(t,i,n?!0:!1):e.detachEvent("on"+t,i)},hui.event=function(e){return void 0!==e&&e.huiEvent===!0?e:new hui.Event(e)},hui.Event=function(e){this.huiEvent=!0,this.event=e=e||window.event,e||hui.log("No event"),this.element=e.target?e.target:e.srcElement,this.shiftKey=e.shiftKey,this.altKey=e.altKey,this.metaKey=e.metaKey,this.returnKey=13==e.keyCode,this.escapeKey=27==e.keyCode,this.spaceKey=32==e.keyCode,this.backspaceKey=8==e.keyCode,this.upKey=38==e.keyCode,this.downKey=40==e.keyCode,this.leftKey=37==e.keyCode,this.rightKey=39==e.keyCode,this.keyCode=e.keyCode},hui.Event.prototype={getLeft:function(){var e=0
return this.event&&(this.event.pageX?e=this.event.pageX:this.event.clientX&&(e=this.event.clientX+hui.window.getScrollLeft())),e},getTop:function(){var e=0
return this.event&&(this.event.pageY?e=this.event.pageY:this.event.clientY&&(e=this.event.clientY+hui.window.getScrollTop())),e},getElement:function(){return this.element},findByClass:function(e){return hui.get.firstAncestorByClass(this.element,e)},findByTag:function(e){for(var t=this.element;t;){if(t.tagName&&t.tagName.toLowerCase()==e)return t
t=t.parentNode}return null},find:function(e){for(var t=this.element;t;){if(t.tagName&&t.tagName.toLowerCase()==tag&&e(t))return t
t=t.parentNode}return null},isDescendantOf:function(e){for(var t=this.element;t;){if(t===e)return!0
t=t.parentNode}return!1},stop:function(){hui.stop(this.event)}},hui.stop=function(e){e||(e=window.event),e.stopPropagation&&e.stopPropagation(),e.preventDefault&&e.preventDefault(),e.cancelBubble=!0,e.stopped=!0},hui._defered=[],hui._ready="complete"==document.readyState,hui.onReady=function(e){hui._ready?e():hui._defered.push(e),1==hui._defered.length&&hui._onReady(function(){hui._ready=!0
for(var e=0;e<hui._defered.length;e++)hui._defered[e]()
hui._defered=null})},hui._onReady=function(e){if(window.addEventListener)window.addEventListener("DOMContentLoaded",e,!1)
else if("undefined"!=typeof document.addEventListener)document.addEventListener("load",e,!1)
else if("undefined"!=typeof window.attachEvent)window.attachEvent("onload",e)
else if("function"==typeof window.onload){var t=window.onload
window.onload=function(){t(),e()}}else window.onload=e},hui.request=function(e){e=hui.override({method:"POST",async:!0,headers:{Ajax:!0}},e)
var t=hui.request.createTransport()
if(t){t.onreadystatechange=function(){try{4==t.readyState&&(200==t.status&&e.$success?e.$success(t):403==t.status&&e.$forbidden?e.$forbidden(t):0!==t.status&&e.$failure?e.$failure(t):0===t.status&&e.$abort&&e.$abort(t),e.$finally&&e.$finally())}catch(i){if(!e.$exception)throw i
e.$exception(i,t)}}
var i=e.method.toUpperCase()
t.open(i,e.url,e.async)
var n=null
if("POST"==i&&e.file){if(n=new FormData,n.append("file",e.file),e.parameters)for(var o in e.parameters)n.append(o,e.parameters[o])
e.$progress&&t.upload.addEventListener("progress",function(t){e.$progress(t.loaded,t.total)},!1),e.$load&&t.upload.addEventListener("load",function(){e.$load()},!1)}else if("POST"==i&&e.files){n=new FormData
for(var s=0;s<e.files.length;s++)n.append("file"+s,e.files[s])}else"POST"==i&&e.parameters?(n=hui.request._buildPostBody(e.parameters),t.setRequestHeader("Content-type","application/x-www-form-urlencoded; charset=utf-8")):n=""
if(e.headers)for(var a in e.headers)t.setRequestHeader(a,e.headers[a])
return t.send(n),t}},hui.request.isXMLResponse=function(e){return e.responseXML&&e.responseXML.documentElement&&"parsererror"!=e.responseXML.documentElement.nodeName},hui.request._buildPostBody=function(e){if(!e)return null
var t,i=""
if(hui.isArray(e))for(var n=0;n<e.length;n++)t=e[n],n>0&&(i+="&"),i+=encodeURIComponent(t.name)+"=",void 0!==t.value&&null!==t.value&&(i+=encodeURIComponent(t.value))
else for(t in e)i.length>0&&(i+="&"),i+=encodeURIComponent(t)+"=",void 0!==e[t]&&null!==e[t]&&(i+=encodeURIComponent(e[t]))
return i},hui.request.createTransport=function(){try{if(window.XMLHttpRequest){var e=new XMLHttpRequest
return null===e.readyState&&(e.readyState=1,e.addEventListener("load",function(){e.readyState=4,"function"==typeof e.onreadystatechange&&e.onreadystatechange()},!1)),e}if(window.ActiveXObject)return hui.request._getActiveX()}catch(t){}return null},hui.request._getActiveX=function(){for(var e=["MSXML2","Microsoft","MSXML","MSXML3"],t=0;t<e.length;t++)try{return new ActiveXObject(e[t]+".XmlHttp")}catch(i){}},hui.style={copy:function(e,t,i){for(var n=0;n<i.length;n++){var o=i[n],s=hui.style.get(e,o)
s&&(t.style[hui.string.camelize(o)]=s)}},set:function(e,t){for(var i in t)"transform"===i?e.style.webkitTransform=t[i]:"opacity"===i?hui.style.setOpacity(e,t[i]):e.style[i]=t[i]},get:function(e,t){e=hui.get(e)
var i=hui.string.camelize(t),n=e.style[i]
if(!n)if(document.defaultView&&document.defaultView.getComputedStyle){var o=document.defaultView.getComputedStyle(e,null)
n=o?o.getPropertyValue(t):null}else e.currentStyle&&(n=e.currentStyle[i])
return window.opera&&hui.array.contains(["left","top","right","bottom"],t)&&"static"==hui.style.get(e,"position")&&(n="auto"),"auto"==n?"":n},setOpacity:function(e,t){hui.browser.opacity?e.style.opacity=t:e.style.filter=1==t?null:"alpha(opacity="+100*t+")"},length:function(e){return"number"==typeof e?e+"px":e}},hui.frame={getDocument:function(e){return e.contentDocument?e.contentDocument:e.contentWindow?e.contentWindow.document:e.document?e.document:void 0},getWindow:function(e){return e.defaultView?e.defaultView:e.contentWindow?e.contentWindow:void 0}},hui.selection={clear:function(){var e
document.selection&&document.selection.empty?document.selection.empty():window.getSelection&&(e=window.getSelection(),e&&e.removeAllRanges&&e.removeAllRanges())},getText:function(e){return e=e||document,e.getSelection?e.getSelection()+"":e.selection?e.selection.createRange().text:""},getNode:function(e){if(e=e||document,e.getSelection){var t=e.getSelection().getRangeAt(0)
return"function"==typeof t.commonAncestorContainer?t.commonAncestorContainer():t.commonAncestorContainer}return null},get:function(e){return{node:hui.selection.getNode(e),text:hui.selection.getText(e)}},enable:function(e){document.onselectstart=e?null:function(){return!1},document.body.style.webkitUserSelect=e?null:"none"}},hui.effect={makeFlippable:function(e){hui.browser.webkit?(hui.cls.add(e.container,"hui_flip_container"),hui.cls.add(e.front,"hui_flip_front"),hui.cls.add(e.back,"hui_flip_back")):(hui.cls.add(e.front,"hui_flip_front_legacy"),hui.cls.add(e.back,"hui_flip_back_legacy"))},flip:function(e){if(hui.browser.webkit){var t=hui.get(e.element),i=e.duration||"1s",n=hui.get.firstByClass(t,"hui_flip_front"),o=hui.get.firstByClass(t,"hui_flip_back")
n.style.webkitTransitionDuration=i,o.style.webkitTransitionDuration=i,hui.cls.toggle(e.element,"hui_flip_flipped")}else hui.cls.toggle(e.element,"hui_flip_flipped_legacy")},bounceIn:function(e){var t=e.element
hui.browser.msie?hui.style.set(t,{display:"block",visibility:"visible"}):(hui.style.set(t,{display:"block",opacity:0,visibility:"visible"}),hui.animate(t,"transform","scale(0.1)",0),window.setTimeout(function(){hui.animate(t,"opacity",1,300),hui.animate(t,"transform","scale(1)",400,{ease:hui.ease.backOut})}))},fadeIn:function(e){var t=e.element
"none"==hui.style.get(t,"display")&&hui.style.set(t,{opacity:0,display:"inherit"}),hui.animate({node:t,css:{opacity:1},delay:e.delay||null,duration:e.duration||500,$complete:e.onComplete||e.$complete})},fadeOut:function(e){hui.animate({node:e.element,css:{opacity:0},delay:e.delay||null,duration:e.duration||500,hideOnComplete:!0,complete:e.onComplete||e.$complete})},wiggle:function(e){hui.ui.getElement(e.element)
hui.cls.add(e.element,"hui_effect_wiggle"),window.setTimeout(function(){hui.cls.remove(e.element,"hui_effect_wiggle")},e.duration||1e3)},shake:function(e){hui.ui.getElement(e.element)
hui.cls.add(e.element,"hui_effect_shake"),window.setTimeout(function(){hui.cls.remove(e.element,"hui_effect_shake")},e.duration||1e3)}},hui.document={getWidth:function(){return Math.max(document.body.clientWidth,document.documentElement.clientWidth,document.documentElement.scrollWidth)},getHeight:function(){if(hui.browser.msie6){for(var e=Math.max(document.body.clientHeight,document.documentElement.clientHeight,document.documentElement.scrollHeight),t=document.body.childNodes,i=0;i<t.length;i++)hui.dom.isElement(t[i])&&(e=Math.max(e,t[i].clientHeight))
return e}return window.scrollMaxY&&window.innerHeight?window.scrollMaxY+window.innerHeight:Math.max(document.body.clientHeight,document.documentElement.clientHeight,document.documentElement.scrollHeight)}},hui.drag={register:function(e){hui.listen(e.element,"mousedown",function(t){e.$check&&e.$check(t)===!1||(hui.stop(t),hui.drag.start(e))})},start:function(e){var t=hui.browser.msie?document:window
e.onStart&&e.onStart()
var i,n,o=!1
i=function(t){t=hui.event(t),t.stop(t),!o&&e.onBeforeMove&&e.onBeforeMove(t),o=!0,e.onMove(t)}.bind(this),hui.listen(t,"mousemove",i),n=function(){hui.unListen(t,"mousemove",i),hui.unListen(t,"mouseup",n),e.onEnd&&e.onEnd(),o&&e.onAfterMove&&e.onAfterMove(),!o&&e.onNotMoved&&e.onNotMoved(),hui.selection.enable(!0)}.bind(this),hui.listen(t,"mouseup",n),hui.selection.enable(!1)},_nativeListeners:[],_activeDrop:null,listen:function(e){hui.browser.msie||(hui.drag._nativeListeners.push(e),hui.drag._nativeListeners.length>1||(hui.listen(document.body,"dragenter",function(e){for(var t=hui.drag._nativeListeners,i=null,n=0;n<t.length;n++){var o=t[n].element
if(hui.dom.isDescendantOrSelf(e.target,o)){i=t[n],(null===hui.drag._activeDrop||hui.drag._activeDrop!=i)&&hui.cls.add(o,i.hoverClass)
break}}hui.drag._activeDrop&&(hui.drag._activeDrop!=i?(hui.cls.remove(hui.drag._activeDrop.element,hui.drag._activeDrop.hoverClass),hui.drag._activeDrop.$leave&&hui.drag._activeDrop.$leave(e)):hui.drag._activeDrop.$hover&&hui.drag._activeDrop.$hover(e)),hui.drag._activeDrop=i}),hui.listen(document.body,"dragover",function(e){hui.stop(e),hui.drag._activeDrop&&hui.drag._activeDrop.$hover&&hui.drag._activeDrop.$hover(e)}),hui.listen(document.body,"dragend",function(){hui.log("drag end")}),hui.listen(document.body,"dragstart",function(){hui.log("drag start")}),hui.listen(document.body,"drop",function(e){var t=hui.event(e)
t.stop()
var i=hui.drag._activeDrop
if(hui.drag._activeDrop=null,i&&(hui.cls.remove(i.element,i.hoverClass),i.$drop&&i.$drop(e,{event:t}),e.dataTransfer))if(hui.log(e.dataTransfer.types),i.$dropFiles&&e.dataTransfer.files&&e.dataTransfer.files.length>0)i.$dropFiles(e.dataTransfer.files,{event:t})
else if(i.$dropURL&&null!==e.dataTransfer.types&&(hui.array.contains(e.dataTransfer.types,"public.url")||hui.array.contains(e.dataTransfer.types,"text/uri-list"))){var n=e.dataTransfer.getData("public.url"),o=e.dataTransfer.getData("text/uri-list")
n&&!hui.string.startsWith(n,"data:")?i.$dropURL(n,{event:t}):o&&!hui.string.startsWith(n,"data:")&&i.$dropURL(o,{event:t})}else i.$dropText&&null!==e.dataTransfer.types&&hui.array.contains(e.dataTransfer.types,"text/plain")&&i.$dropText(e.dataTransfer.getData("text/plain"),{event:t})})))}},hui.Preloader=function(e){this.options=e||{},this.delegate={},this.images=[],this.loaded=0},hui.Preloader.prototype={addImages:function(e){if("object"==typeof e)for(var t=0;t<e.length;t++)this.images.push(e[t])
else this.images.push(e)},setDelegate:function(e){this.delegate=e},load:function(e){e=e||0
var t=this
this.obs=[]
for(var i=function(){t._imageChanged(this.huiPreloaderIndex,"imageDidLoad")},n=function(){t._imageChanged(this.huiPreloaderIndex,"imageDidGiveError")},o=function(){t._imageChanged(this.huiPreloaderIndex,"imageDidAbort")},s=e;s<this.images.length+e;s++){var a=s
a>=this.images.length&&(a-=this.images.length)
var r=new Image
r.huiPreloaderIndex=a,r.onload=i,r.onerror=n,r.onabort=o,r.src=(this.options.context?this.options.context:"")+this.images[a],this.obs.push(r)}},_imageChanged:function(e,t){this.loaded++,this.delegate[t]&&this.delegate[t](this.loaded,this.images.length,e),this.loaded==this.images.length&&this.delegate.allImagesDidLoad&&this.delegate.allImagesDidLoad()}},hui.cookie={set:function(e,t,i){var n
if(i){var o=new Date
o.setTime(o.getTime()+24*i*60*60*1e3),n="; expires="+o.toGMTString()}else n=""
document.cookie=e+"="+t+n+"; path=/"},get:function(e){for(var t=e+"=",i=document.cookie.split(";"),n=0;n<i.length;n++){for(var o=i[n];" "==o.charAt(0);)o=o.substring(1,o.length)
if(0===o.indexOf(t))return o.substring(t.length,o.length)}return null},clear:function(e){this.set(e,"",-1)}},hui.location={getParameter:function(e){for(var t=hui.location.getParameters(),i=0;i<t.length;i++)if(t[i].name==e)return t[i].value
return null},setParameter:function(e,t){for(var i=hui.location.getParameters(),n=!1,o=0;o<i.length;o++)if(i[o].name==e){i[o].value=t,n=!0
break}n||i.push({name:e,value:t}),hui.location.setParameters(i)},hasHash:function(e){var t=document.location.hash
return""!==t?t=="#"+e:!1},getHash:function(){var e=document.location.hash
return""!==e?e.substring(1):null},getHashParameter:function(e){var t=document.location.hash
if(""!==t){var i=t.indexOf(e+"=")
if(-1!==i){var n=t.substring(i+e.length+1)
return-1!==n.indexOf("&")?n.substring(0,n.indexOf("&")):n}}return null},clearHash:function(){document.location.hash="#"},setParameters:function(e){for(var t="",i=0;i<e.length;i++)t+=0===i?"?":"&",t+=e[i].name+"="+e[i].value
document.location.search=t},getBoolean:function(e){var t=hui.location.getParameter(e)
return"true"==t||"1"==t},getInt:function(e){var t=parseInt(hui.location.getParameter(e))
return isNaN(t)?null:t},getParameters:function(){for(var e=document.location.search.substring(1).split("&"),t=[],i=0;i<e.length;i++){var n=e[i].split("="),o=unescape(n[0]).replace(/^\s*|\s*$/g,""),s=unescape(n[1]).replace(/^\s*|\s*$/g,"")
o&&t.push({name:o,value:s})}return t}},window.define&&define("hui"),hui.animate=function(e,t,i,n,o){if("string"==typeof e||hui.dom.isElement(e))hui.animation.get(e).animate(null,i,t,n,o)
else{var s=hui.animation.get(e.node)
if(e.property)s.animate(null,e.value,e.property,e.duration,e)
else if(e.css){var a=e
for(var r in e.css)s.animate(null,e.css[r],r,e.duration,a),a=hui.override({},e),a.$complete=void 0}else s.animate(null,"","",e.duration,e)}},hui.animation={objects:{},running:!1,latestId:0,get:function(e){return e=hui.get(e),e.huiAnimationId||(e.huiAnimationId=this.latestId++),this.objects[e.huiAnimationId]||(this.objects[e.huiAnimationId]=new hui.animation.Item(e)),this.objects[e.huiAnimationId]},start:function(){this.running||hui.animation._render()}},hui.animation._lengthUpater=function(e,t,i){e.style[i.property]=i.from+(i.to-i.from)*t+(null!=i.unit?i.unit:"")},hui.animation._transformUpater=function(e,t,i){var n=i.transform,o=""
n.rotate&&(o+=" rotate("+(n.rotate.from+(n.rotate.to-n.rotate.from)*t)+n.rotate.unit+")"),n.scale&&(o+=" scale("+(n.scale.from+(n.scale.to-n.scale.from)*t)+")"),e.style[hui.animation.TRANSFORM]=o},hui.animation._colorUpater=function(e,t,i){var n=Math.round(i.from.red+(i.to.red-i.from.red)*t),o=Math.round(i.from.green+(i.to.green-i.from.green)*t),s=Math.round(i.from.blue+(i.to.blue-i.from.blue)*t)
value="rgb("+n+","+o+","+s+")",e.style[i.property]=value},hui.animation._propertyUpater=function(e,t,i){e[i.property]=Math.round(i.from+(i.to-i.from)*t)},hui.animation._ieOpacityUpdater=function(e,t,i){var n=i.from+(i.to-i.from)*t
1==n?e.style.removeAttribute("filter"):e.style.filter="alpha(opacity="+100*n+")"},hui.animation._render=function(){hui.animation.running=!0
var e=!1,t=(new Date).getTime()
for(var i in hui.animation.objects){var n=hui.animation.objects[i]
if(n.work)for(var o=n.element,s=0;s<n.work.length;s++){var a=n.work[s]
if(!a.finished){var r=(t-a.start)/(a.end-a.start)
if(0>r)e=!0
else{isNaN(r)||r>1?r=1:1>r&&(e=!0)
var u=r
a.delegate&&a.delegate.ease&&(u=a.delegate.ease(u)),a.delegate&&a.delegate.$render?a.delegate.$render(o,u):a.delegate&&a.delegate.callback?a.delegate.callback(o,u):a.updater&&a.updater(o,u,a),1==r&&(a.finished=!0,a.delegate&&a.delegate.$complete?window.setTimeout(a.delegate.$complete):a.delegate&&a.delegate.onComplete?window.setTimeout(a.delegate.onComplete):a.delegate&&a.delegate.hideOnComplete&&(o.style.display="none"))}}}}e?window.requestAnimationFrame(hui.animation._render):hui.animation.running=!1},hui.animation._parseStyle=function(e){var t,i={type:null,value:null,unit:null}
if(!hui.isDefined(e))return i
if(isNaN(e))if(t=e.match(/([\-]?[0-9\.]+)(px|pt|%)/))i.type="length",i.value=parseFloat(t[1]),i.unit=t[2]
else if(t=e.match(/rgb\(([0-9]+),[ ]?([0-9]+),[ ]?([0-9]+)\)/))i.type="color",i.value={red:parseInt(t[1]),green:parseInt(t[2]),blue:parseInt(t[3])}
else{var n=new hui.Color(e)
n.ok&&(i.value={red:n.r,green:n.g,blue:n.b})}else i.value=parseFloat(e)
return i},hui.animation.Item=function(e){this.element=e,this.work=[]},hui.animation.Item.prototype.animate=function(e,t,i,n,o){var s=this.getWork(hui.string.camelize(i))
s.delegate=o,s.finished=!1
var a=!("scrollLeft"==i||"scrollTop"==i||""==i)
if(null!==e)s.from=e
else if("transform"==i)s.transform=hui.animation.Item.parseTransform(t,this.element)
else if(hui.browser.opacity||"opacity"!=i)if(a){var r=hui.style.get(this.element,i),u=hui.animation._parseStyle(r)
s.from=u.value}else s.from=this.element[i]
else s.from=this._getIEOpacity(this.element)
if(a){var h=hui.animation._parseStyle(t)
s.to=h.value,s.unit=h.unit,s.updater=hui.browser.opacity||"opacity"!=i?"transform"==i?hui.browser.msie?function(){}:hui.animation._transformUpater:"color"==h.type?hui.animation._colorUpater:hui.animation._lengthUpater:hui.animation._ieOpacityUpdater}else s.to=t,s.unit=null,s.updater=hui.animation._propertyUpater
s.start=(new Date).getTime(),o&&o.delay&&(s.start+=o.delay),s.end=s.start+n,hui.animation.start()},hui.animation.TRANSFORM=hui.browser.gecko?"MozTransform":"WebkitTransform",hui.animation.Item.parseTransform=function(e,t){var i,n,o={},s=/rotate\(([0-9\.]+)([a-z]+)\)/i,a=e.match(s)
a&&(i=0,t.style[hui.animation.TRANSFORM]&&(n=t.style[hui.animation.TRANSFORM].match(s),n&&(i=parseFloat(n[1]))),o.rotate={from:i,to:parseFloat(a[1]),unit:a[2]})
var r=/scale\(([0-9\.]+)\)/i,u=e.match(r)
return u&&(i=1,t.style[hui.animation.TRANSFORM]&&(n=t.style[hui.animation.TRANSFORM].match(r),n&&(i=parseFloat(n[1]))),o.scale={from:i,to:parseFloat(u[1])}),o},hui.animation.Item.prototype._getIEOpacity=function(e){var t,i=hui.style.get(e,"filter").toLowerCase()
return(t=i.match(/opacity=([0-9]+)/))?parseFloat(t[1])/100:1},hui.animation.Item.prototype.getWork=function(e){for(var t=this.work.length-1;t>=0;t--)if(this.work[t].property===e)return this.work[t]
var i={property:e}
return this.work[this.work.length]=i,i},hui.animation.Loop=function(e){this.recipe=e,this.position=-1,this.running=!1},hui.animation.Loop.prototype.next=function(){this.position++,this.position>=this.recipe.length&&(this.position=0)
var e=this.recipe[this.position]
"function"==typeof e?e():e.element&&hui.animate(e.element,e.property,e.value,e.duration,{ease:e.ease})
var t=this,i=e.duration||0
void 0!==e.wait&&(i=e.wait),window.setTimeout(function(){t.next()},i)},hui.animation.Loop.prototype.start=function(){this.running=!0,this.next()},hui.ease={slowFastSlow:function(e){var t=1.6,i=1.4
return-1*Math.pow(Math.cos(Math.PI/2*Math.pow(e,t)),Math.pow(Math.PI,i))+1},fastSlow:function(e){var t=.5,i=.7
return-1*Math.pow(Math.cos(Math.PI/2*Math.pow(e,t)),Math.pow(Math.PI,i))+1},elastic:function(e){return 1-hui.ease.elastic2(1-e)},elastic2:function(e,t,i){if(0>=e||e>=1)return e
i||(i=.45)
var n
return!t||1>t?(t=1,n=i/4):n=i/(2*Math.PI)*Math.asin(1/t),-(t*Math.pow(2,10*(e-=1))*Math.sin(2*(e-n)*Math.PI/i))},bounce:function(e){return 1/2.75>e?7.5625*e*e:2/2.75>e?7.5625*(e-=1.5/2.75)*e+.75:2.5/2.75>e?7.5625*(e-=2.25/2.75)*e+.9375:7.5625*(e-=2.625/2.75)*e+.984375},flicker:function(e){return 1==e?1:Math.random()*e},linear:function(e){return e},quadIn:function(e){return Math.pow(e,2)},quadOut:function(e){return e*(e-2)*-1},quadInOut:function(e){return e=2*e,1>e?Math.pow(e,2)/2:-1*(--e*(e-2)-1)/2},cubicIn:function(e){return Math.pow(e,3)},cubicOut:function(e){return Math.pow(e-1,3)+1},cubicInOut:function(e){return e=2*e,1>e?Math.pow(e,3)/2:(e-=2,(Math.pow(e,3)+2)/2)},quartIn:function(e){return Math.pow(e,4)},quartOut:function(e){return-1*(Math.pow(e-1,4)-1)},quartInOut:function(e){return e=2*e,1>e?Math.pow(e,4)/2:(e-=2,-0.5*(Math.pow(e,4)-2))},quintIn:function(e){return Math.pow(e,5)},quintOut:function(e){return Math.pow(e-1,5)+1},quintInOut:function(e){return e=2*e,1>e?Math.pow(e,5)/2:(e-=2,(Math.pow(e,5)+2)/2)},sineIn:function(e){return-1*Math.cos(e*(Math.PI/2))+1},sineOut:function(e){return Math.sin(e*(Math.PI/2))},sineInOut:function(e){return-1*(Math.cos(Math.PI*e)-1)/2},expoIn:function(e){return 0==e?0:Math.pow(2,10*(e-1))},expoOut:function(e){return 1==e?1:-1*Math.pow(2,-10*e)+1},expoInOut:function(e){return 0==e?0:1==e?1:(e=2*e,1>e?Math.pow(2,10*(e-1))/2:(--e,(-1*Math.pow(2,-10*e)+2)/2))},circIn:function(e){return-1*(Math.sqrt(1-Math.pow(e,2))-1)},circOut:function(e){return e-=1,Math.sqrt(1-Math.pow(e,2))},circInOut:function(e){return e=2*e,1>e?-0.5*(Math.sqrt(1-Math.pow(e,2))-1):(e-=2,.5*(Math.sqrt(1-Math.pow(e,2))+1))},backIn:function(e){var t=1.70158
return Math.pow(e,2)*((t+1)*e-t)},backOut:function(e){e-=1
var t=1.70158
return Math.pow(e,2)*((t+1)*e+t)+1},backInOut:function(e){var t=2.5949095
return e=2*e,1>e?Math.pow(e,2)*((t+1)*e-t)/2:(e-=2,(Math.pow(e,2)*((t+1)*e+t)+2)/2)},elasticIn:function(e){if(0==e)return 0
if(1==e)return 1
var t=.3,i=t/4
return e-=1,-1*Math.pow(2,10*e)*Math.sin(2*(e-i)*Math.PI/t)},elasticOut:function(e){if(0==e)return 0
if(1==e)return 1
var t=.3,i=t/4
return Math.pow(2,-10*e)*Math.sin(2*(e-i)*Math.PI/t)+1},elasticInOut:function(e){if(0==e)return 0
if(e=2*e,2==e)return 1
var t=.3*1.5,i=t/4
return 1>e?(e-=1,-.5*Math.pow(2,10*e)*Math.sin(2*(e-i)*Math.PI/t)):(e-=1,.5*Math.pow(2,-10*e)*Math.sin(2*(e-i)*Math.PI/t)+1)},bounceIn:function(e){return 1-hui.ease.bounceOut(1-e)},bounceOut:function(e){var t,i=7.5625,n=2.75
return 1/n>e?t=i*Math.pow(e,2):2/n>e?(e-=1.5/n,t=i*Math.pow(e,2)+.75):2.5/n>e?(e-=2.25/n,t=i*Math.pow(e,2)+.9375):(e-=2.625/n,t=i*Math.pow(e,2)+.984375),t},bounceInOut:function(e){return.5>e?hui.ease.bounceIn(2*e)/2:hui.ease.bounceOut(2*e-1)/2+.5}},function(){var e=0,t=["ms","moz","webkit","o"]
if(!hui.browser.chrome)for(var i=0;i<t.length&&!window.requestAnimationFrame;++i)window.requestAnimationFrame=window[t[i]+"RequestAnimationFrame"],window.cancelAnimationFrame=window[t[i]+"CancelAnimationFrame"]||window[t[i]+"CancelRequestAnimationFrame"]
window.requestAnimationFrame||(window.requestAnimationFrame=function(t){var i=(new Date).getTime(),n=Math.max(0,16-(i-e)),o=window.setTimeout(function(){t(i+n)},0)
return e=i+n,o}),window.cancelAnimationFrame||(window.cancelAnimationFrame=function(e){clearTimeout(e)})}(),hui.Color=function(e){if(this.ok=!1,!hui.isBlank(e)){"#"==e.charAt(0)&&(e=e.substr(1,6)),e=e.replace(/ /g,""),e=e.toLowerCase()
for(var t in hui.Color.table)e==t&&(e=hui.Color.table[t])
for(var i=[{re:/^rgb\((\d{1,3}),\s*(\d{1,3}),\s*(\d{1,3})\)$/,process:function(e){return[parseInt(e[1]),parseInt(e[2]),parseInt(e[3])]}},{re:/^rgb\((\d{1,3})%,\s*(\d{1,3})%,\s*(\d{1,3})%\)$/,process:function(e){return[Math.round(parseInt(e[1])/100*255),Math.round(parseInt(e[2])/100*255),Math.round(parseInt(e[3])/100*255)]}},{re:/^(\w{2})(\w{2})(\w{2})$/,process:function(e){return[parseInt(e[1],16),parseInt(e[2],16),parseInt(e[3],16)]}},{re:/^(\w{1})(\w{1})(\w{1})$/,process:function(e){return[parseInt(e[1]+e[1],16),parseInt(e[2]+e[2],16),parseInt(e[3]+e[3],16)]}}],n=0;n<i.length;n++){var o=i[n].re,s=i[n].process,a=o.exec(e)
if(a){var r=s(a)
this.r=r[0],this.g=r[1],this.b=r[2],this.ok=!0
break}}this.r=this.r<0||isNaN(this.r)?0:this.r>255?255:this.r,this.g=this.g<0||isNaN(this.g)?0:this.g>255?255:this.g,this.b=this.b<0||isNaN(this.b)?0:this.b>255?255:this.b}},hui.Color.prototype={toRGB:function(){return"rgb("+this.r+", "+this.g+", "+this.b+")"},isDefined:function(){return!(void 0===this.r||void 0===this.g||void 0===this.b)},toHex:function(){if(!this.isDefined())return null
var e=this.r.toString(16),t=this.g.toString(16),i=this.b.toString(16)
return 1==e.length&&(e="0"+e),1==t.length&&(t="0"+t),1==i.length&&(i="0"+i),"#"+e+t+i}},hui.Color.table={white:"ffffff",black:"000000",red:"ff0000",green:"00ff00",blue:"0000ff"},hui.Color.hex2rgb=function(e){if(hui.isBlank(e))return null
if("#"==e[0]&&(e=e.substr(1)),3==e.length){var t=e
e="",t=/^([a-f0-9])([a-f0-9])([a-f0-9])$/i.exec(t).slice(1)
for(var i=0;3>i;i++)e+=t[i]+t[i]}var n=/^([a-f0-9]{2})([a-f0-9]{2})([a-f0-9]{2})$/i.exec(e).slice(1)
return{r:parseInt(n[0],16),g:parseInt(n[1],16),b:parseInt(n[2],16)}},hui.Color.hsv2rgb=function(e,t,i){var n,o,s,a=e/360
if(0==t)n=255*i,o=255*i,s=255*i
else{var r,u,h,l=6*a,d=Math.floor(l),c=i*(1-t),f=i*(1-t*(l-d)),g=i*(1-t*(1-(l-d)))
0==d?(r=i,u=g,h=c):1==d?(r=f,u=i,h=c):2==d?(r=c,u=i,h=g):3==d?(r=c,u=f,h=i):4==d?(r=g,u=c,h=i):(r=i,u=c,h=f),n=Math.round(255*r),o=Math.round(255*u),s=Math.round(255*h)}return new Array(n,o,s)},hui.Color.rgb2hsv=function(e,t,i){e/=255,t/=255,i/=255
var n,o,s=Math.min(Math.min(e,t),i),a=Math.max(Math.max(e,t),i),r=a
return a==s?o=0:a==e?o=60*((t-i)/(a-s))%360:a==t?o=60*((i-e)/(a-s))+120:a==i&&(o=60*((e-t)/(a-s))+240),0>o&&(o+=360),n=0==a?0:1-s/a,[Math.round(o),Math.round(100*n),Math.round(100*r)]},hui.Color.rgb2hex=function(e){for(var t="#",i=0;3>i;i++){var n=parseInt(e[i]).toString(16)
n.length<2&&(n="0"+n),t+=n}return t},!function(e,t,i){function n(e,t){m(e,function(e){return!t(e)})}function o(e,i){var n=t.createElement("script"),o=l
n.onload=n.onerror=n[p]=function(){n[f]&&!/^c|loade/.test(n[f])||o||(n.onload=n[p]=null,o=1,i())},n.async=1,n.src=e,s.insertBefore(n,s.firstChild)}var s=t.getElementsByTagName("head")[0],a={},r={},u={},h={},l=!1,d="push",c="DOMContentLoaded",f="readyState",g="addEventListener",p="onreadystatechange",m=function(e,t){for(var i=0,n=e.length;n>i;++i)if(!t(e[i]))return l
return 1}
!t[f]&&t[g]&&(t[g](c,function w(){t.removeEventListener(c,w,l),t[f]="complete"},l),t[f]="loading")
var v=function(e,t,s){function l(e){return e.call?e():a[e]}function c(){if(!--y){a[p]=1,g&&g()
for(var e in u)m(e.split("|"),l)&&!n(u[e],l)&&(u[e]=[])}}e=e[d]?e:[e]
var f=t&&t.call,g=f?t:s,p=f?e.join(""):t,y=e.length
return i(function(){n(e,function(e){return h[e]?(p&&(r[p]=1),void c()):(h[e]=1,p&&(r[p]=1),void o(v.path?v.path+e+".js":e,c))})},0),v}
v.get=o,v.ready=function(e,t,i){e=e[d]?e:[e]
var o=[]
return!n(e,function(e){a[e]||o[d](e)})&&m(e,function(e){return a[e]})?t():!function(e){u[e]=u[e]||[],u[e][d](t),i&&i(o)}(e.join("|")),v}
var y=e.$script
v.noConflict=function(){return e.$script=y,this},"undefined"!=typeof module&&module.exports?module.exports=v:e.hui.require=v}(this,document,setTimeout),hui.parallax={_listeners:[],_init:function(){this._listening||(this._listening=!0,hui.listen(window,"scroll",this._scroll.bind(this)),hui.listen(window,"resize",this._resize.bind(this)))},_resize:function(){for(var e=this._listeners.length-1;e>=0;e--){var t=this._listeners[e]
t.$resize&&t.$resize(hui.window.getViewWidth(),hui.window.getViewHeight())}this._scroll()},_scroll:function(){for(var e=hui.window.getScrollTop(),t=hui.window.getViewHeight(),i=this._listeners.length-1;i>=0;i--){var n=this._listeners[i]
if(n.$scroll)if(n.debug&&!n.debugElement&&(n.debugElement=hui.build("div",{style:"position: absolute; border-top: 1px solid red; left: 0; right: 0;",parent:document.body})),n.element){var o=hui.position.getTop(n.element)
o+=n.element.clientHeight/2
var s=o-e,a=s/t
n.debugElement&&(n.debugElement.style.top=o+"px",n.debugElement.innerHTML="<span>"+a+"</span>"),n.$scroll(a)}else{var r=(e-n.min)/(n.max-n.min),u=hui.between(0,r,1)
n._latest!==u&&(n.$scroll(u),n._latest=u)}}},listen:function(e){this._listeners.push(e)},start:function(){this._init(),this._resize()}},hui.ui={domReady:!1,context:"",language:"en",objects:{},delegates:[],state:"default",latestObjectIndex:0,latestIndex:500,latestPanelIndex:1e3,latestAlertIndex:1500,latestTopIndex:2e3,toolTips:{},confirmOverlays:{},delayedUntilReady:[],texts:{request_error:{en:"An error occurred on the server",da:"Der skete en fejl på serveren"},"continue":{en:"Continue",da:"Fortsæt"},reload_page:{en:"Reload page",da:"Indæs siden igen"},access_denied:{en:"Access denied, maybe you are nolonger logged in",da:"Adgang nægtet, du er måske ikke længere logget ind"}}},hui.ui.get=function(e){return e?e.element?e:hui.ui.objects[e]:null},hui.ui.onReady=function(e){return hui.ui.domReady?e():hui.browser.gecko&&hui.string.endsWith(document.baseURI,"xml")?void window.setTimeout(e,1e3):void hui.ui.delayedUntilReady.push(e)},hui.ui._frameLoaded=function(e){hui.ui.callSuperDelegates(this,"frameLoaded",e)},hui.ui._resize=function(){hui.ui.reLayout(),window.clearTimeout(this._delayedResize),hui.ui._resizeFirst||(this._delayedResize=window.setTimeout(hui.ui._afterResize,1e3))},hui.ui._afterResize=function(){hui.ui.callSuperDelegates(hui.ui,"$afterResize")},hui.ui.confirmOverlay=function(e){var t,i=e.element
i||(i=document.body),e.widget&&(i=e.widget.getElement()),hui.ui.confirmOverlays[i]?(t=hui.ui.confirmOverlays[i],t.clear()):(t=hui.ui.Overlay.create({modal:!0}),hui.ui.confirmOverlays[i]=t),e.text&&t.addText(hui.ui.getTranslated(e.text))
var n=hui.ui.Button.create({text:hui.ui.getTranslated(e.okText)||"OK",highlighted:"true"})
n.click(function(){e.onOk?e.onOk():e.$ok&&e.$ok(),t.hide()}),t.add(n)
var o=hui.ui.Button.create({text:hui.ui.getTranslated(e.cancelText)||"Cancel"})
o.onClick(function(){e.onCancel?e.onCancel():e.$cancel&&e.$cancel(),t.hide()}),t.add(o),t.show({element:i})},hui.ui.destroy=function(e){"function"==typeof e.destroy&&e.destroy(),delete hui.ui.objects[e.name]},hui.ui.destroyDescendants=function(e){for(var t=hui.ui.getDescendants(e),i=(hui.ui.objects,0);i<t.length;i++)hui.ui.destroy(t[i])},hui.ui.getAncestors=function(e){var t=[],i=e.element
if(i){var n=hui.get.ancestors(i),o=[]
for(var s in hui.ui.objects)o.push(hui.ui.objects[s])
for(var a=0;a<n.length;a++)for(var r=0;r<o.length;r++)o[r].element==n[a]&&t.push(o[r])}return t},hui.ui.getDescendants=function(e){var t=[],i=e.getElement?e.getElement():e
if(i){var n=i.getElementsByTagName("*"),o=[]
for(var s in hui.ui.objects)o.push(hui.ui.objects[s])
for(var a=0;a<n.length;a++)for(var r=0;r<o.length;r++)n[a]==o[r].element&&t.push(o[r])}return t},hui.ui.getAncestor=function(e,t){for(var i=hui.ui.getAncestors(e),n=0;n<i.length;n++)if(hui.cls.has(i[n].getElement(),t))return i[n]
return null},hui.ui.changeState=function(e){if(hui.ui.state!==e){var t,i,n=hui.ui.objects
for(t in n)i=n[t],i.options&&i.options.state&&(i.options.state==e?i.show():i.hide())
hui.ui.state=e,this.reLayout()}},hui.ui.reLayout=function(){for(var e=hui.ui.getDescendants(document.body),t=0;t<e.length;t++){var i=e[t]
i.$$layout&&i.$$layout()}},hui.ui.nextIndex=function(){return hui.ui.latestIndex++,hui.ui.latestIndex},hui.ui.nextPanelIndex=function(){return hui.ui.latestPanelIndex++,hui.ui.latestPanelIndex},hui.ui.nextAlertIndex=function(){return hui.ui.latestAlertIndex++,hui.ui.latestAlertIndex},hui.ui.nextTopIndex=function(){return hui.ui.latestTopIndex++,hui.ui.latestTopIndex},hui.ui.showCurtain=function(e){var t=e.widget
if(!t.curtain){t.curtain=hui.build("div",{"class":"hui_curtain",style:"z-index:none"})
var i=hui.get.firstByClass(document.body,"hui_body")
i||(i=document.body),i.appendChild(t.curtain),hui.listen(t.curtain,"click",function(){t.$curtainWasClicked&&t.$curtainWasClicked()})}var n=t.curtain
if(e.transparent)n.style.background="none"
else if(e.color)if("auto"==e.color){var o=hui.style.get(document.body,"background-color");("transparent"==o||"rgba(0, 0, 0, 0)"==o)&&(o="#fff"),n.style.backgroundColor=o}else n.style.backgroundColor=e.color
hui.browser.msie?n.style.height=hui.document.getHeight()+"px":(n.style.position="fixed",n.style.top="0",n.style.left="0",n.style.bottom="0",n.style.right="0"),n.style.zIndex=e.zIndex,e.transparent?n.style.display="block":(hui.style.setOpacity(n,0),n.style.display="block",hui.animate(n,"opacity",.7,1e3,{ease:hui.ease.slowFastSlow}))},hui.ui.hideCurtain=function(e){e.curtain&&hui.animate(e.curtain,"opacity",0,200,{hideOnComplete:!0})},hui.ui.getText=function(e){var t=this.texts[e]
return t?t[this.language]?t[this.language]:t.en:e},hui.ui.getTranslated=function(e){if(!hui.isDefined(e)||hui.isString(e)||"number"==typeof e)return e
if(e[hui.ui.language])return e[hui.ui.language]
if(e[null])return e[null]
for(var t in e)return e[t]},hui.ui.confirm=function(e){e.name||(e.name="huiConfirm")
var t,i=hui.ui.get(e.name)
if(i)i.update(e),t=hui.ui.get(name+"_ok"),t.setText(e.ok||"OK"),t.setHighlighted("ok"==e.highlighted),t.clearListeners(),hui.ui.get(name+"_cancel").setText(e.ok||"Cancel"),hui.ui.get(name+"_cancel").setHighlighted("cancel"==e.highlighted),e.cancel&&hui.ui.get(name+"_cancel").setText(e.cancel)
else{i=hui.ui.Alert.create(e)
var n=hui.ui.Button.create({name:name+"_cancel",text:e.cancel||"Cancel",highlighted:"cancel"===e.highlighted})
n.listen({$click:function(){i.hide(),e.onCancel&&e.onCancel(),hui.ui.callDelegates(i,"cancel")}}),i.addButton(n),t=hui.ui.Button.create({name:name+"_ok",text:e.ok||"OK",highlighted:"ok"===e.highlighted}),i.addButton(t)}t.listen({$click:function(){i.hide(),e.onOK&&e.onOK(),hui.ui.callDelegates(i,"ok")}}),i.show()},hui.ui.alert=function(e){this.alertBox?this.alertBox.update(e):(this.alertBox=hui.ui.Alert.create(e),this.alertBoxButton=hui.ui.Button.create({name:"huiAlertBoxButton",text:"OK"}),this.alertBoxButton.listen({$click$huiAlertBoxButton:function(){hui.ui.alertBox.hide(),hui.ui.alertBoxCallBack&&(hui.ui.alertBoxCallBack(),hui.ui.alertBoxCallBack=null)}}),this.alertBox.addButton(this.alertBoxButton)),this.alertBoxCallBack=e.onOK,this.alertBoxButton.setText(e.button?e.button:"OK"),this.alertBox.show()},hui.ui.showMessage=function(e){if("string"==typeof e&&(e={text:e}),e.delay)return void(hui.ui.messageDelayTimer=window.setTimeout(function(){e.delay=null,hui.ui.showMessage(e)},e.delay))
window.clearTimeout(hui.ui.messageDelayTimer),hui.ui.message||(hui.ui.message=hui.build("div",{"class":"hui_message",html:"<div><div></div></div>"}),hui.browser.msie||hui.style.setOpacity(hui.ui.message,0),document.body.appendChild(hui.ui.message))
var t=hui.ui.getTranslated(e.text)||"",i=hui.ui.message.getElementsByTagName("div")[1]
e.icon?(hui.dom.clear(i),i.appendChild(hui.ui.createIcon(e.icon,24)),hui.dom.addText(i,t)):e.busy?(i.innerHTML='<span class="hui_message_busy"></span>',hui.dom.addText(i,t)):hui.dom.setText(i,t),hui.ui.message.style.display="block",hui.ui.message.style.zIndex=hui.ui.nextTopIndex(),hui.ui.message.style.marginLeft=hui.ui.message.clientWidth/-2+"px",hui.ui.message.style.marginTop=hui.window.getScrollTop()+"px",hui.browser.opacity&&hui.animate(hui.ui.message,"opacity",1,300),window.clearTimeout(hui.ui.messageTimer),e.duration&&(hui.ui.messageTimer=window.setTimeout(hui.ui.hideMessage,e.duration))},hui.ui.msg=hui.ui.showMessage,hui.ui.msg.success=function(e){e=hui.override({icon:"common/success",duration:2e3},e),hui.ui.msg(e)},hui.ui.msg.fail=function(e){e=hui.override({icon:"common/warning",duration:3e3},e),hui.ui.msg(e)},hui.ui.hideMessage=function(){window.clearTimeout(hui.ui.messageDelayTimer),hui.ui.message&&(hui.browser.opacity?hui.animate(hui.ui.message,"opacity",0,300,{hideOnComplete:!0}):hui.ui.message.style.display="none")},hui.ui.showToolTip=function(e){var t=e.key||"common",i=hui.ui.toolTips[t]
i||(i=hui.build("div",{"class":"hui_tooltip",style:"display:none;",html:"<div><div></div></div>",parent:document.body}),hui.ui.toolTips[t]=i),i.onclick=function(){hui.ui.hideToolTip(e)}
var n=hui.get(e.element),o=hui.position.get(n)
hui.dom.setText(i.getElementsByTagName("div")[1],e.text),"none"==i.style.display&&hui.browser.opacity&&hui.style.setOpacity(i,0),hui.style.set(i,{display:"block",zIndex:hui.ui.nextTopIndex()}),hui.style.set(i,{left:o.left-i.clientWidth+4+"px",top:o.top+2-i.clientHeight/2+n.clientHeight/2+"px"}),hui.browser.opacity&&hui.animate(i,"opacity",1,300)},hui.ui.hideToolTip=function(e){var t=e?e.key||"common":"common",i=hui.ui.toolTips[t]
i&&(hui.browser.msie?i.style.display="none":hui.animate(i,"opacity",0,300,{hideOnComplete:!0}))},hui.ui.getElement=function(e){return hui.dom.isElement(e)?e:e.getElement?e.getElement():null},hui.ui.isWithin=function(e,t){e=hui.event(e)
var i=hui.position.get(t),n={width:t.offsetWidth,height:t.offsetHeight},o=e.getLeft(),s=e.getTop()
return o>i.left&&o<i.left+n.width&&s>i.top&&s<i.top+n.height},hui.ui.getIconUrl=function(e,t){return hui.ui.context+"/hui/icons/"+e+t+".png"},hui.ui.createIcon=function(e,t,i){return hui.build(i||"span",{"class":"hui_icon hui_icon_"+t,style:"background-image: url("+hui.ui.getIconUrl(e,t)+")"})},hui.ui.wrapInField=function(e){var t=hui.build("div",{"class":"hui_field",html:'<span class="hui_field_top"><span><span></span></span></span><span class="hui_field_middle"><span class="hui_field_middle"><span class="hui_field_content"></span></span></span><span class="hui_field_bottom"><span><span></span></span></span>'})
return hui.get.firstByClass(t,"hui_field_content").appendChild(e),t},hui.ui.addFocusClass=function(e){var t=e.classElement||e.element,i=e["class"]
hui.listen(e.element,"focus",function(){hui.cls.add(t,i),e.widget&&hui.ui.setKeyboardTarget(e.widget)}),hui.listen(e.element,"blur",function(){hui.cls.remove(t,i),e.widget&&hui.ui.setKeyboardTarget(null)})},hui.ui.keyboardTarget=null,hui.ui.setKeyboardTarget=function(e){hui.ui.keyboardTarget=e},hui.ui.stress=function(e){var t=hui.ui.getElement(e)
hui.effect.wiggle({element:t,duration:1e3})},hui.ui.positionAtElement=function(e,t,i){i=i||{},e=hui.get(e),t=hui.get(t)
var n=hui.style.get(e,"display")
"none"==n&&hui.style.set(e,{visibility:"hidden",display:"block"})
var o=hui.position.getLeft(t),s=hui.position.getTop(t),a=i.vertical||null
i.horizontal&&"right"==i.horizontal&&(o=o+t.clientWidth-e.clientWidth),"topOutside"==a?s-=e.clientHeight:"bottomOutside"==a&&(s+=t.clientHeight),o+=i.left||0,s+=i.top||0,hui.style.set(e,{left:o+"px",top:s+"px"}),"none"==n&&hui.style.set(e,{visibility:"visible",display:"none"})},hui.ui.extend=function(e,t){e.name||(hui.ui.latestObjectIndex++,e.name="unnamed"+hui.ui.latestObjectIndex),void 0!==t&&(e.options&&(e.options=hui.override(e.options,t)),e.element=hui.get(t.element),e.name=t.name),hui.ui.objects[e.name]&&hui.log("Widget replaced: "+e.name,hui.ui.objects[e.name]),hui.ui.objects[e.name]=e,e.delegates=[],e.listen=function(e){return hui.array.add(this.delegates,e),this},e.unListen=function(e){hui.array.remove(this.delegates,e)},e.clearListeners=function(){this.delegates=[]},e.fire=function(e,t,i){return hui.ui.callDelegates(this,e,t,i)},e.fireValueChange=function(){e.fire("valueChanged",e.value),hui.ui.firePropertyChange(e,"value",e.value),hui.ui.callAncestors(e,"childValueChanged",e.value)},e.fireProperty=function(e,t){hui.ui.firePropertyChange(this,e,t)},e.fireSizeChange=function(){hui.ui.callAncestors(e,"$$childSizeChanged")},e.getElement||(e.getElement=function(){return this.element}),e.destroy||(e.destroy=function(){this.element&&hui.dom.remove(this.element)}),e.valueForProperty||(e.valueForProperty=function(e){return this[e]})},hui.ui.callAncestors=function(e,t,i,n){"undefined"==typeof i&&(i=e)
for(var o=hui.ui.getAncestors(e),s=0;s<o.length;s++)o[s][t]&&o[s][t](i,n)},hui.ui.callDescendants=function(e,t,i,n){"undefined"==typeof i&&(i=e),"$"!==t[0]&&(t="$"+t)
for(var o=hui.ui.getDescendants(e),s=0;s<o.length;s++)o[s][t]&&o[s][t](i,n)},hui.ui.callVisible=function(e){hui.ui.callDescendants(e,"$visibilityChanged")},hui.ui.listen=function(e){hui.ui.domReady&&e.$ready&&e.$ready(),hui.ui.delegates.push(e)},hui.ui.unListen=function(e){hui.array.remove(hui.ui.delegates,e)},hui.ui.callDelegates=function(e,t,i,n){"undefined"==typeof i&&(i=e)
var o
if(e.delegates)for(var s=0;s<e.delegates.length;s++){var a,r=e.delegates[s],u="$"+t+"$"+e.name
e.name&&r[u]?a=r[u](i,n):r["$"+t]&&(a=r["$"+t](i,n)),void 0===o&&void 0!==a&&"undefined"!=typeof a&&(o=a)}var h=hui.ui.callSuperDelegates(e,t,i,n)
return void 0===o&&void 0!==h&&(o=h),o},hui.ui.tellContainers=function(e,t){if(window.parent!=window)try{window.parent.hui.ui._tellContainers(e,t)}catch(i){}},hui.ui._tellContainers=function(e,t){if(hui.ui.callSuperDelegates({},e,t),window.parent!=window)try{window.parent.hui.ui._tellContainers(e,t)}catch(i){}},hui.ui.callSuperDelegates=function(e,t,i,n){"undefined"==typeof i&&(i=e)
for(var o,s=0;s<hui.ui.delegates.length;s++){var a,r=hui.ui.delegates[s]
e.name&&r["$"+t+"$"+e.name]?a=r["$"+t+"$"+e.name](i,n):r["$"+t]&&(a=r["$"+t](i,n)),void 0===o&&void 0!==a&&"undefined"!=typeof a&&(o=a)}return o},hui.ui.resolveImageUrl=function(e,t,i,n){for(var o=0;o<e.delegates.length;o++)if(e.delegates[o].$resolveImageUrl)return e.delegates[o].$resolveImageUrl(t,i,n)
for(var s=0;s<hui.ui.delegates.length;s++){var a=hui.ui.delegates[s]
if(a.$resolveImageUrl)return a.$resolveImageUrl(t,i,n)}return null},hui.ui.include=function(e){hui.ui.request({url:e.url,$text:function(t){var i=hui.build("div",{html:t,parent:document.body})
hui.dom.runScripts(i),e.$success()}})},hui.ui.firePropertyChange=function(e,t,i){hui.ui.callDelegates(e,"propertyChanged",{property:t,value:i})},hui.ui.bind=function(e,t){if(hui.isString(e)&&"@"==e.charAt(0)){var i=e.substring(1).split("."),n=hui.ui.get(i[0])
if(!n)return void hui.log("Unable to bind to "+e)
var o=i.slice(1).join(".")
return n.listen({$propertyChanged:function(e){e.property==o&&t(e.value)}}),n.valueForProperty(o)}return e},hui.ui.handleRequestError=function(e){hui.log("General request error received")
var t=hui.ui.callSuperDelegates(e||this,"requestError")
t||hui.ui.confirmOverlay({element:document.body,text:hui.ui.getText("request_error"),okText:hui.ui.getText("reload_page"),cancelText:hui.ui.getText("continue"),onOk:function(){document.location.reload()}})},hui.ui.handleForbidden=function(e){hui.log("General access denied received")
var t=hui.ui.callSuperDelegates(e||this,"accessDenied")
t||hui.ui.confirmOverlay({element:document.body,text:hui.ui.getText("access_denied"),okText:hui.ui.getText("reload_page"),cancelText:hui.ui.getText("continue"),onOk:function(){document.location.reload()}})},hui.ui.request=function(e){if(e=hui.override({method:"post",parameters:{}},e),e.json)for(var t in e.json)e.parameters[t]=hui.string.toJSON(e.json[t])
var i=e.$success,n=e.$object,o=e.$text,s=e.$xml,a=e.$failure,r=e.$forbidden,u=e.message
e.$success=function(e){u&&(u.success?hui.ui.showMessage({text:u.success,icon:"common/success",duration:u.duration||2e3}):u.start&&hui.ui.hideMessage())
var t,a
"string"==typeof i?hui.request.isXMLResponse(e)?hui.ui.callDelegates(e,"success$"+i):(t=e.responseText.replace(/^\s+|\s+$/g,""),a=t.length>0?hui.string.fromJSON(e.responseText):"",hui.ui.callDelegates(a,"success$"+i)):s&&hui.request.isXMLResponse(e)?s(e.responseXML):n?(t=e.responseText.replace(/^\s+|\s+$/g,""),a=t.length>0?hui.string.fromJSON(e.responseText):null,n(a)):"function"==typeof i?i(e):o&&o(e.responseText)},e.$failure=function(t){"string"==typeof a?hui.ui.callDelegates(t,"failure$"+a):"function"==typeof a?a(t):(e.message&&e.message.start&&hui.ui.hideMessage(),hui.ui.handleRequestError())},e.$exception=e.$exception||function(e,t){throw hui.log(e),hui.log(t),e},e.$forbidden=function(t){e.message&&e.message.start&&hui.ui.hideMessage(),r?r(t):(e.$failure(t),hui.ui.handleForbidden())},e.message&&e.message.start&&hui.ui.msg({text:e.message.start,busy:!0,delay:e.message.delay}),hui.request(e)},hui.ui.parseItems=function(e){var t=e.documentElement,i=[]
return hui.ui.parseSubItems(t,i),i},hui.ui.parseSubItems=function(e,t){for(var i=e.childNodes,n=0;n<i.length;n++){var o=i[n]
if(1==o.nodeType&&"title"==o.nodeName)t.push({title:o.getAttribute("title"),type:"title"})
else if(1==o.nodeType&&"item"==o.nodeName){var s=[]
hui.ui.parseSubItems(o,s),t.push({text:o.getAttribute("text"),title:o.getAttribute("title"),value:o.getAttribute("value"),icon:o.getAttribute("icon"),kind:o.getAttribute("kind"),badge:o.getAttribute("badge"),children:s})}}},hui.ui.require=function(e,t){for(var i=e.length-1;i>=0;i--)e[i]=hui.ui.context+"hui/js/"+e[i]+".js"
hui.require(e,t)},window.define&&define("hui.ui"),hui.onReady(function(){hui.listen(window,"resize",hui.ui._resize),hui.ui.reLayout(),hui.ui.domReady=!0,window.parent&&window.parent.hui&&window.parent.hui.ui&&window.parent.hui.ui._frameLoaded(window)
for(var e=0;e<hui.ui.delayedUntilReady.length;e++)hui.ui.delayedUntilReady[e]()
hui.ui.callSuperDelegates(this,"ready")}),hui.ui.ImageViewer=function(e){this.options=hui.override({maxWidth:800,maxHeight:600,perimeter:100,sizeSnap:100,margin:0,ease:hui.ease.slowFastSlow,easeEnd:hui.ease.bounce,easeAuto:hui.ease.slowFastSlow,easeReturn:hui.ease.cubicInOut,transition:400,transitionEnd:1e3,transitionReturn:300,images:[]},e),this.element=hui.get(e.element),this.box=this.options.box,this.viewer=hui.get.firstByClass(this.element,"hui_imageviewer_viewer"),this.innerViewer=hui.get.firstByClass(this.element,"hui_imageviewer_inner_viewer"),this.status=hui.get.firstByClass(this.element,"hui_imageviewer_status"),this.previousControl=hui.get.firstByClass(this.element,"hui_imageviewer_previous"),this.controller=hui.get.firstByClass(this.element,"hui_imageviewer_controller"),this.nextControl=hui.get.firstByClass(this.element,"hui_imageviewer_next"),this.playControl=hui.get.firstByClass(this.element,"hui_imageviewer_play"),this.closeControl=hui.get.firstByClass(this.element,"hui_imageviewer_close"),this.text=hui.get.firstByClass(this.element,"hui_imageviewer_text"),this.dirty=!1,this.width=600,this.height=460,this.index=0,this.playing=!1,this.name=e.name,this.images=e.images,this.box.listen(this),this._addBehavior(),hui.ui.extend(this),e.listener&&this.listen(e.listener)},hui.ui.ImageViewer.create=function(e){e=e||{}
var t=e.element=hui.build("div",{"class":"hui_imageviewer",html:'<div class="hui_imageviewer_viewer"><div class="hui_imageviewer_inner_viewer"></div></div><div class="hui_imageviewer_text"></div><div class="hui_imageviewer_status"></div><div class="hui_imageviewer_controller"><div><div><a class="hui_imageviewer_previous"></a><a class="hui_imageviewer_play"></a><a class="hui_imageviewer_next"></a><a class="hui_imageviewer_close"></a></div></div></div>'}),i=e.box=hui.ui.Box.create({absolute:!0,modal:!0,closable:!0})
return i.add(t),i.addToDocument(),new hui.ui.ImageViewer(e)},hui.ui.ImageViewer.prototype={_addBehavior:function(){var e=this
this.nextControl.onclick=function(){e.next(!0)},this.previousControl.onclick=function(){e.previous(!0)},this.playControl.onclick=function(){e.playOrPause()},this.closeControl.onclick=this.hide.bind(this),hui.listen(this.viewer,"click",this._zoom.bind(this)),this._timer=function(){e.next(!1)},this._keyListener=function(t){t=hui.event(t),t.rightKey?e.next(!0):t.leftKey?e.previous(!0):t.escapeKey?e.hide():t.returnKey&&e.playOrPause()},hui.listen(this.viewer,"mousemove",this._onMouseMove.bind(this)),hui.listen(this.controller,"mouseover",function(){e.overController=!0}),hui.listen(this.controller,"mouseout",function(){e.overController=!1}),hui.listen(this.viewer,"mouseout",function(t){hui.ui.isWithin(t,this.viewer)||e._hideController()}.bind(this))},_onMouseMove:function(){window.clearTimeout(this.ctrlHider),this._shouldShowController()&&(this.ctrlHider=window.setTimeout(this._hideController.bind(this),2e3),hui.browser.msie?this.controller.style.display="block":hui.effect.fadeIn({element:this.controller,duration:200}))},_hideController:function(){this.overController||(hui.browser.msie?this.controller.style.display="none":hui.effect.fadeOut({element:this.controller,duration:500}))},_getLargestSize:function(e,t){return t.width<=e.width&&t.height<=e.height?{width:t.width,height:t.height}:e.width/e.height>t.width/t.height?{width:Math.round(e.height/t.height*t.width),height:e.height}:e.width/e.height<t.width/t.height?{width:e.width,height:Math.round(e.width/t.width*t.height)}:{width:e.width,height:e.height}},_calculateSize:function(){var e=this.options.sizeSnap,t=hui.window.getViewWidth()-this.options.perimeter
t=Math.floor(t/e)*e,t=Math.min(t,this.options.maxWidth)
var i=hui.window.getViewHeight()-this.options.perimeter
i=Math.floor(i/e)*e,i=Math.min(i,this.options.maxHeight)
for(var n=0,o=0,s=0;s<this.images.length;s++){var a=this._getLargestSize({width:t,height:i},this.images[s])
n=Math.max(n,a.width),o=Math.max(o,a.height)}i=Math.floor(Math.min(i,o)),t=Math.floor(Math.min(t,n)),(t!=this.width||i!=this.height)&&(this.width=t,this.height=i,this.dirty=!0)},_updateUI:function(){if(this.dirty){this.innerViewer.innerHTML=""
for(var e=0;e<this.images.length;e++){var t=hui.build("div",{"class":"hui_imageviewer_image"})
hui.style.set(t,{width:this.width+this.options.margin+"px",height:this.height-1+"px"}),this.innerViewer.appendChild(t)}this.controller.style.display=this._shouldShowController()?"block":"none",this.dirty=!1,this._preload()}},_shouldShowController:function(){return this.images.length>1},_goToImage:function(e,t,i){if(e)if(t>1)hui.animate(this.viewer,"scrollLeft",this.index*(this.width+this.options.margin),Math.min(t*this.options.transitionReturn,2e3),{ease:this.options.easeReturn})
else{var n=0==this.index||this.index==this.images.length-1,o=n?this.options.easeEnd:this.options.ease
i||(o=this.options.easeAuto),hui.animate(this.viewer,"scrollLeft",this.index*(this.width+this.options.margin),n?this.options.transitionEnd:this.options.transition,{ease:o})}else this.viewer.scrollLeft=this.index*(this.width+this.options.margin)
var s=this.images[this.index].text
s?(this.text.innerHTML=s,this.text.style.display="block"):(this.text.innerHTML="",this.text.style.display="none")},showById:function(e){for(var t=0;t<this.images.length;t++)if(this.images[t].id==e){this.show(t)
break}},show:function(e){this.index=e||0,this._calculateSize(),this._updateUI()
var t=this.options.margin
hui.style.set(this.element,{width:this.width+t+"px",height:this.height+2*t-1+"px"}),hui.style.set(this.viewer,{width:this.width+t+"px",height:this.height-1+"px"}),hui.style.set(this.innerViewer,{width:(this.width+t)*this.images.length+"px",height:this.height-1+"px"}),hui.style.set(this.controller,{marginLeft:(this.width-180)/2+.5*t+"px",display:"none"}),this.box.show(),this._goToImage(!1,0,!1),hui.listen(document,"keydown",this._keyListener),this.visible=!0,this._setHash(!0)},_setHash:function(e){},_onHashChange:function(){this._changing||(this._changing=!0,hui.location.hasHash("imageviewer")&&!this.visible?this.show():!hui.location.hasHash("imageviewer")&&this.visible&&this.hide(),this._changing=!1)},hide:function(){this._hide()},_hide:function(){this.pause(),this.box.hide(),hui.unListen(document,"keydown",this._keyListener),this.visible=!1,this._setHash(!1)},$boxCurtainWasClicked:function(){this.hide()},$boxWasClosed:function(){this.hide()},clearImages:function(){this.images=[],this.dirty=!0},addImages:function(e){for(var t=0;t<e.length;t++)this.addImage(e[t])},addImage:function(e){this.images.push(e),this.dirty=!0},play:function(){this.interval||(this.interval=window.setInterval(this._timer,6e3)),this.next(!1),this.playing=!0,this.playControl.className="hui_imageviewer_pause"},pause:function(){window.clearInterval(this.interval),this.interval=null,this.playControl.className="hui_imageviewer_play",this.playing=!1},playOrPause:function(){this.playing?this.pause():this.play()},_resetPlay:function(){this.playing&&(window.clearInterval(this.interval),this.interval=window.setInterval(this._timer,6e3))},previous:function(e){var t=1
this.index--,this.index<0&&(this.index=this.images.length-1,t=this.images.length-1),this._goToImage(!0,t,e),this._resetPlay()},next:function(e){var t=1
this.index++,this.index==this.images.length&&(this.index=0,t=this.images.length-1),this._goToImage(!0,t,e),this._resetPlay()},_preload:function(){var e=new hui.Preloader
e.addImages(hui.ui.context+"/hui/gfx/imageviewer_controls.png")
var t=this
e.setDelegate({allImagesDidLoad:function(){t._preloadImages()}}),e.load()},_preloadImages:function(){var e=new hui.Preloader
e.setDelegate(this)
for(var t=0;t<this.images.length;t++){var i=hui.ui.resolveImageUrl(this,this.images[t],this.width,this.height)
null!==i&&e.addImages(i)}this.status.innerHTML="0%",this.status.style.display="",e.load(this.index)},allImagesDidLoad:function(){this.status.style.display="none"},imageDidLoad:function(e,t,i){this.status.innerHTML=Math.round(e/t*100)+"%"
var n=hui.ui.resolveImageUrl(this,this.images[i],this.width,this.height)
n=n.replace(/&amp;/g,"&"),this.innerViewer.childNodes[i].style.backgroundImage="url('"+n+"')",hui.cls.set(this.innerViewer.childNodes[i],"hui_imageviewer_image_abort",!1),hui.cls.set(this.innerViewer.childNodes[i],"hui_imageviewer_image_error",!1)},imageDidGiveError:function(e,t,i){hui.cls.set(this.innerViewer.childNodes[i],"hui_imageviewer_image_error",!0)},imageDidAbort:function(e,t,i){hui.cls.set(this.innerViewer.childNodes[i],"hui_imageviewer_image_abort",!0)},_zoom:function(e){var t=this.images[this.index]
if(!(t.width<=this.width&&t.height<=this.height)){this.zoomer||(this.zoomer=hui.build("div",{"class":"hui_imageviewer_zoomer",style:"width:"+this.viewer.clientWidth+"px;height:"+this.viewer.clientHeight+"px"}),this.element.insertBefore(this.zoomer,hui.dom.firstChild(this.element)),hui.listen(this.zoomer,"mousemove",this._onZoomMove.bind(this)),hui.listen(this.zoomer,"click",function(){this.zoomer.style.display="none"}.bind(this))),this.pause()
var i=this._getLargestSize({width:2e3,height:2e3},t),n=hui.ui.resolveImageUrl(this,t,i.width,i.height)
this.zoomer.innerHTML='<div style="width:'+i.width+"px;height:"+i.height+'px; margin: 0 auto;"><img src="'+n+'"/></div>',this.zoomer.style.display="block",this.zoomInfo={width:i.width,height:i.height},this._onZoomMove(e)}},_onZoomMove:function(e){if(e=new hui.Event(e),this.zoomInfo){var t={left:hui.position.getLeft(this.zoomer),top:hui.position.getTop(this.zoomer)},i=(e.getLeft()-t.left)/this.zoomer.clientWidth*(this.zoomInfo.width-this.zoomer.clientWidth),n=(e.getTop()-t.top)/this.zoomer.clientHeight*(this.zoomInfo.height-this.zoomer.clientHeight)
this.zoomer.scrollLeft=i,this.zoomer.scrollTop=n}}},hui.ui.Box=function(e){this.options=hui.override({},e),this.name=e.name,this.element=hui.get(e.element),this.body=hui.get.firstByClass(this.element,"hui_box_body"),this.close=hui.get.firstByClass(this.element,"hui_box_close"),this.visible=!this.options.absolute,this.close&&hui.listen(this.close,"click",this._close.bind(this)),hui.ui.extend(this)},hui.ui.Box.create=function(e){return e=e||{},e.element=hui.build("div",{"class":e.absolute?"hui_box hui_box_absolute":"hui_box",html:(e.closable?'<a class="hui_box_close" href="#"></a>':"")+'<div class="hui_box_top"><div><div></div></div></div><div class="hui_box_middle"><div class="hui_box_middle">'+(e.title?'<div class="hui_box_header"><strong class="hui_box_title">'+hui.string.escape(hui.ui.getTranslated(e.title))+"</strong></div>":"")+'<div class="hui_box_body" style="'+(e.padding?"padding: "+e.padding+"px;":"")+(e.width?"width: "+e.width+"px;":"")+'"></div></div></div><div class="hui_box_bottom"><div><div></div></div></div>',style:e.width?e.width+"px":null}),new hui.ui.Box(e)},hui.ui.Box.prototype={_close:function(e){hui.stop(e),this.hide(),this.fire("boxWasClosed"),this.fire("close")},shake:function(){hui.effect.shake({element:this.element})},addToDocument:function(){document.body.appendChild(this.element)},add:function(e){this.body.appendChild(e.getElement?e.getElement():e)},show:function(){var e=this.element
if(this.options.modal){var t=hui.ui.nextPanelIndex()
e.style.zIndex=t+1,hui.ui.showCurtain({widget:this,zIndex:t})}if(this.options.absolute){hui.style.set(e,{display:"block",visibility:"hidden"})
var i=e.clientWidth,n=(hui.window.getViewHeight()-e.clientHeight)/2+hui.window.getScrollTop()
hui.style.set(e,{marginLeft:i/-2+"px",top:n+"px"}),hui.style.set(e,{display:"block",visibility:"visible"})}else e.style.display="block"
this.visible=!0,hui.ui.callVisible(this)},isVisible:function(){return this.visible},$$layout:function(){if(this.options.absolute&&this.visible){var e=this.element,t=e.clientWidth,i=(hui.window.getViewHeight()-e.clientHeight)/2+hui.window.getScrollTop()
hui.style.set(e,{marginLeft:t/-2+"px",top:i+"px"})}},hide:function(){hui.ui.hideCurtain(this),this.element.style.display="none",this.visible=!1,hui.ui.callVisible(this)},$curtainWasClicked:function(){this.fire("boxCurtainWasClicked"),this.options.curtainCloses&&this._close()}},hui.ui.SearchField=function(e){this.options=hui.override({expandedWidth:null},e),this.element=hui.get(e.element),this.name=e.name,this.field=hui.get.firstByTag(this.element,"input"),this.value=this.field.value,this.adaptive=hui.cls.has(this.element,"hui_searchfield_adaptive"),this.initialWidth=null,hui.ui.extend(this),this._addBehavior(),""!==this.value&&this._updateClass()},hui.ui.SearchField.create=function(e){return e=e||{},e.element=hui.build("span",{"class":e.adaptive?"hui_searchfield hui_searchfield_adaptive":"hui_searchfield",html:'<em class="hui_searchfield_placeholder"></em><a href="javascript:void(0);" class="hui_searchfield_reset"></a><span><span><input type="text"/></span></span>'}),new hui.ui.SearchField(e)},hui.ui.SearchField.prototype={_addBehavior:function(){var e=this
hui.listen(this.field,"keyup",this._onKeyUp.bind(this))
var t=hui.get.firstByTag(this.element,"a")
if(t.tabIndex=-1,hui.browser.ipad){var i=function(){e.field.focus()}
hui.listen(hui.get.firstByTag(this.element,"em"),"click",i)}else{var i=function(){e.field.focus(),e.field.select()}
hui.listen(this.element,"mousedown",i),hui.listen(this.element,"mouseup",i),hui.listen(hui.get.firstByTag(this.element,"em"),"mousedown",i)}hui.listen(t,"mousedown",function(t){hui.stop(t),e.reset(),i()}),hui.listen(this.field,"focus",this._onFocus.bind(this)),hui.listen(this.field,"blur",this._onBlur.bind(this))},_onFocus:function(){hui.ui.setKeyboardTarget(this),this.focused=!0,this._updateClass(),this.options.expandedWidth>0&&(null==this.initialWidth&&(this.initialWidth=parseInt(hui.style.get(this.element,"width"))),hui.animate(this.element,"width",this.options.expandedWidth+"px",500,{ease:hui.ease.slowFastSlow}))},_onBlur:function(){hui.ui.setKeyboardTarget(null),this.focused=!1,this._updateClass(),null!==this.initialWidth&&hui.animate(this.element,"width",this.initialWidth+"px",500,{ease:hui.ease.slowFastSlow,delay:100})},_onKeyUp:function(e){this._fieldChanged(),e.keyCode===hui.KEY_RETURN&&this.fire("submit")},focus:function(){this.field.focus()},setValue:function(e){this.field.value=void 0===e||null===e?"":e,this._fieldChanged()},getValue:function(){return this.field.value},isEmpty:function(){return""==this.field.value},isBlank:function(){return hui.isBlank(this.field.value)},reset:function(){this.field.value="",this._fieldChanged()},_updateClass:function(){var e="hui_searchfield"
this.adaptive&&(e+=" hui_searchfield_adaptive"),this.focused&&""!=this.value?e+=" hui_searchfield_focus_dirty":this.focused?e+=" hui_searchfield_focus":""!=this.value&&(e+=" hui_searchfield_dirty"),this.element.className=e},_fieldChanged:function(){this.field.value!=this.value&&(this.value=this.field.value,this._updateClass(),this.fireValueChange())}},hui.ui.Overlay=function(e){this.options=e,this.element=hui.get(e.element),this.content=hui.get.byClass(this.element,"hui_inner_overlay")[1],this.name=e.name,this.icons={},this.visible=!1,hui.ui.extend(this),this._addBehavior()},hui.ui.Overlay.create=function(e){e=e||{}
var t=e.element=hui.build("div",{className:"hui_overlay"+(e.variant?" hui_overlay_"+e.variant:""),style:"display:none",html:'<div class="hui_inner_overlay"><div class="hui_inner_overlay"></div></div>'})
return document.body.appendChild(t),new hui.ui.Overlay(e)},hui.ui.Overlay.prototype={_addBehavior:function(){},addIcon:function(e,t){var i=this,n=hui.build("div",{className:"hui_overlay_icon"})
n.style.backgroundImage="url("+hui.ui.getIconUrl(t,32)+")",hui.listen(n,"click",function(t){i._iconWasClicked(e,t)}),this.icons[e]=n,this.content.appendChild(n)},addText:function(e){this.content.appendChild(hui.build("span",{"class":"hui_overlay_text",text:e}))},add:function(e){this.content.appendChild(e.getElement())},hideIcons:function(e){for(var t=0;t<e.length;t++)this.icons[e[t]].style.display="none"},showIcons:function(e){for(var t=0;t<e.length;t++)this.icons[e[t]].style.display=""},_iconWasClicked:function(e,t){hui.ui.callDelegates(this,"iconWasClicked",e,t)},showAtElement:function(e,t){if(t=t||{},hui.ui.positionAtElement(this.element,e,t),t.autoHide&&this._autoHide(e),!this.visible){hui.browser.msie?this.element.style.display="block":(hui.style.set(this.element,{display:"block",opacity:0}),hui.animate(this.element,"opacity",1,150))
var i=void 0===t.zIndex?t.zIndex:hui.ui.nextAlertIndex()
this.options.modal?(this.element.style.zIndex=hui.ui.nextAlertIndex(),hui.ui.showCurtain({widget:this,zIndex:i})):this.element.style.zIndex=i,this.visible=!0}},_autoHide:function(e){hui.cls.add(e,"hui_overlay_bound"),hui.unListen(document.body,"mousemove",this._hider),this._hider=function(t){if(!hui.ui.isWithin(t,e)&&!hui.ui.isWithin(t,this.element))try{hui.unListen(document.body,"mousemove",this._hider),hui.cls.remove(e,"hui_overlay_bound"),this.hide()}catch(t){hui.log("unable to stop listening: document="+document)}}.bind(this),hui.listen(document.body,"mousemove",this._hider)},show:function(e){if(e=e||{},this.visible||hui.style.set(this.element,{display:"block",visibility:"hidden"}),e.element&&hui.position.place({source:{element:this.element,vertical:0,horizontal:.5},target:{element:e.element,vertical:.5,horizontal:.5},insideViewPort:!0,viewPartMargin:9}),e.autoHide&&e.element&&this._autoHide(e.element),!this.visible&&(hui.effect.bounceIn({element:this.element}),this.visible=!0,this.options.modal)){var t=hui.ui.nextAlertIndex()
this.element.style.zIndex=t+1,hui.ui.showCurtain({widget:this,zIndex:t,color:"auto"})}},$curtainWasClicked:function(){this.hide()},hide:function(){hui.ui.hideCurtain(this),this.element.style.display="none",this.visible=!1},clear:function(){hui.ui.destroyDescendants(this.content),this.content.innerHTML=""}},hui.ui.Button=function(e){this.options=e,this.name=e.name,this.element=hui.get(e.element),this.enabled=!hui.cls.has(this.element,"hui_button_disabled"),hui.ui.extend(this),this._attach(),e.listener&&this.listen(e.listener)},hui.ui.Button.create=function(e){e=hui.override({text:"",highlighted:!1,enabled:!0},e)
var t="hui_button"+(e.highlighted?" hui_button_highlighted":"")
e.variant&&(t+=" hui_button_"+e.variant),e.small&&e.variant&&(t+=" hui_button_small_"+e.variant),e.small&&(t+=" hui_button_small"+(e.highlighted?" hui_button_small_highlighted":"")),e.enabled||(t+=" hui_button_disabled")
var i=e.text?hui.ui.getTranslated(e.text):null
e.title&&(i=hui.ui.getTranslated(e.title))
var n=e.element=hui.build("a",{"class":t,href:"javascript://"}),o=hui.build("span",{parent:hui.build("span",{parent:n})})
if(e.icon){var s=hui.build("em",{parent:o,"class":"hui_button_icon",style:"background-image:url("+hui.ui.getIconUrl(e.icon,16)+")"})
i||hui.cls.add(s,"hui_button_icon_notext")}return i&&hui.dom.addText(o,i),new hui.ui.Button(e)},hui.ui.Button.prototype={_attach:function(){var e=this
hui.listen(this.element,"mousedown",function(e){hui.stop(e)}),hui.listen(this.element,"click",function(t){hui.stop(t),e._onClick(t)})},_onClick:function(e){if(this.enabled){var t=!1
e&&(t=hui.event(e).altKey),this.options.confirm&&!t?hui.ui.confirmOverlay({widget:this,text:this.options.confirm.text,okText:this.options.confirm.okText,cancelText:this.options.confirm.cancelText,onOk:this._fireClick.bind(this)}):this._fireClick()}else this.element.blur()},_fireClick:function(){if(this.fire("click",this),this.options.submit){var e=hui.ui.getAncestor(this,"hui_formula")
e?e.submit():hui.log("No form found to submit")}},click:function(e){return e?(this.listen({$click:e}),this):void this._onClick()},focus:function(){this.element.focus()},onClick:function(e){this.listen({$click:e})},setEnabled:function(e){this.enabled=e,this._updateUI()},enable:function(){this.setEnabled(!0)},disable:function(){this.setEnabled(!1)},setHighlighted:function(e){hui.cls.set(this.element,"hui_button_highlighted",e)},_updateUI:function(){hui.cls.set(this.element,"hui_button_disabled",!this.enabled)},setText:function(e){hui.dom.setText(this.element.getElementsByTagName("span")[1],hui.ui.getTranslated(e))},getData:function(){return this.options.data}},hui.ui.Buttons=function(e){this.name=e.name,this.element=hui.get(e.element),this.body=hui.get.firstByClass(this.element,"hui_buttons_body"),hui.ui.extend(this)},hui.ui.Buttons.create=function(e){e=hui.override({top:0},e)
var t=e.element=hui.build("div",{"class":"hui_buttons"})
return"right"===e.align&&hui.cls.add(t,"hui_buttons_right"),"center"===e.align&&hui.cls.add(t,"hui_buttons_center"),e.top>0&&(t.style.paddingTop=e.top+"px"),hui.build("div",{"class":"hui_buttons_body",parent:t}),new hui.ui.Buttons(e)},hui.ui.Buttons.prototype={add:function(e){return this.body.appendChild(e.element),this}},!op)var op={}
op.preview=!1,op.page=op.page||{id:null,path:null,template:null},op.ignite=function(){if(this.preview||(document.onkeydown=function(e){if(e=hui.event(e),e.returnKey&&e.shiftKey){e.stop()
var t
t=function(e){e=hui.event(e),e.returnKey&&(hui.unListen(document,"keyup",t),hui.browser.msie||op.user.internal?window.location=op.page.path+"Editor/index.php?page="+op.page.id:(e.stop(),op.showLogin()))},hui.listen(document,"keyup",t)}return!0},hui.request({url:op.context+"services/statistics/",parameters:{page:op.page.id,referrer:document.referrer,uri:document.location.href}})),hui.browser.msie7&&hui.onReady(function(){hui.cls.add(document.body.parentNode,"msie7")}),hui.browser.msie7||hui.browser.msie6){for(var e=hui.get.byClass(document.body,"shared_frame"),t=0;t<e.length;t++)e[t].style.width=e[t].clientWidth+"px",e[t].style.display="block"
for(var i=hui.get.byClass(document.body,"document_row"),t=i.length-1;t>=0;t--){for(var n=hui.build("table",{"class":i[t].className,style:i[t].style.cssText}),o=hui.build("tbody",{parent:n}),s=hui.build("tr",{parent:o}),a=hui.get.byClass(i[t],"document_column"),r=0;r<a.length;r++)for(var u=a[r],h=hui.build("td",{"class":u.className,parent:s,style:u.style.cssText});u.firstChild;)h.appendChild(u.firstChild)
i[t].parentNode.insertBefore(n,i[t]),hui.dom.remove(i[t])}}},op.showLogin=function(){if(this.loginBox)this.loginBox.show(),this.loginForm.focus()
else{if(this.loadingLogin)return void hui.log("Aborting, the box is loading")
this.loadingLogin=!0,hui.ui.showMessage({text:{en:"Loading...",da:"Indlæser..."},busy:!0,delay:300}),hui.ui.require(["Formula","Button","TextField"],function(){hui.ui.hideMessage()
var e=this.loginBox=hui.ui.Box.create({width:300,title:{en:"Access control",da:"Adgangskontrol"},modal:!0,absolute:!0,closable:!0,curtainCloses:!0,padding:10})
this.loginBox.addToDocument()
var t=this.loginForm=hui.ui.Formula.create()
t.listen({$submit:function(){if(e.isVisible()){var i=t.getValues()
op.login(i.username,i.password)}}})
var i=t.buildGroup(null,[{type:"TextField",options:{label:{en:"Username",da:"Brugernavn"},key:"username"}},{type:"TextField",options:{label:{en:"Password",da:"Kodeord"},key:"password",secret:!0}}]),n=i.createButtons(),o=hui.ui.Button.create({text:{en:"Forgot password?",da:"Glemt kode?"}})
o.listen({$click:function(){document.location=op.context+"Editor/Authentication.php?forgot=true"}}),n.add(o)
var s=hui.ui.Button.create({text:{en:"Cancel",da:"Annuller"}})
s.listen({$click:function(){t.reset(),e.hide(),document.body.focus()}}),n.add(s),n.add(hui.ui.Button.create({text:{en:"Log in",da:"Log ind"},highlighted:!0,submit:!0})),this.loginBox.add(t),this.loginBox.show(),window.setTimeout(function(){t.focus()},100),this.loadingLogin=!1,op.startListening()
var a=new hui.Preloader({context:hui.ui.context+"hui/icons/"})
a.addImages("common/success24.png"),a.load()}.bind(this))}},op.startListening=function(){hui.listen(window,"keyup",function(e){if(e=hui.event(e),e.escapeKey&&this.loginBox.isVisible()){this.loginBox.hide()
var t=hui.get.firstByTag(document.body,"a")
t&&(t.focus(),t.blur()),document.body.blur()}}.bind(this))},op.login=function(e,t){return hui.isBlank(e)||hui.isBlank(t)?(hui.ui.showMessage({text:{en:"Please fill in both fields",da:"Udfyld venligst begge felter"},duration:3e3}),void this.loginForm.focus()):void hui.ui.request({message:{start:{en:"Logging in...",da:"Logger ind..."},delay:300},url:op.context+"Editor/Services/Core/Authentication.php",parameters:{username:e,password:t},$object:function(e){e.success?(hui.ui.showMessage({text:{en:"You are now logged in",da:"Du er nu logget ind"},icon:"common/success",duration:4e3}),op.igniteEditor()):hui.ui.showMessage({text:{en:"The user was not found",da:"Brugeren blev ikke fundet"},icon:"common/warning",duration:4e3})},$failure:function(){hui.ui.showMessage({text:{en:"An internal error occurred",da:"Der skete en fejl internt i systemet"},icon:"common/warning",duration:4e3})}})},op.igniteEditor=function(){window.location=op.page.path+"Editor/index.php?page="+op.page.id},op.showImage=function(e){this.imageViewer||(this.imageViewer=hui.ui.ImageViewer.create({maxWidth:2e3,maxHeight:2e3,perimeter:40,sizeSnap:10}),this.imageViewer.listen(op.imageViewerDelegate)),this.imageViewer.clearImages(),this.imageViewer.addImage(e),this.imageViewer.show()},op.registerImageViewer=function(e,t){hui.get(e).onclick=function(){return op.showImage(t),!1}},op.imageViewerDelegate={$resolveImageUrl:function(e,t,i){var n=e.width?Math.min(t,e.width):t,o=e.height?Math.min(i,e.height):i
return op.page.path+"services/images/?id="+e.id+"&width="+n+"&height="+o+"&format=jpg&quality=100"}},void 0===op.part&&(op.part={}),op.feedback=function(e){hui.require(op.page.path+"style/basic/js/Feedback.js",function(){op.feedback.Controller.init(e)})},window.define&&define("op"),op.part.Formula=function(e){this.element=hui.get(e.element),this.id=e.id,this.inputs=e.inputs,hui.listen(this.element,"submit",this._send.bind(this))},op.part.Formula.prototype={_send:function(e){hui.stop(e)
for(var t=[],i=0;i<this.inputs.length;i++){var n=this.inputs[i],o=hui.get(n.id),s=n.validation
if(s.required&&hui.isBlank(o.value))return hui.ui.showMessage({text:s.message,duration:2e3}),void o.focus()
if("email"==s.syntax&&!hui.isBlank(o.value)){var a=/^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\\n".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA\n-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/
if(!a.test(o.value))return hui.ui.showMessage({text:s.message,duration:2e3}),void o.focus()}t.push({label:n.label,value:o.value})}var r=op.page.path+"services/parts/formula/",u={id:this.id,fields:t}
hui.ui.showMessage({text:"Sender besked...",busy:!0}),hui.ui.request({url:r,json:{data:u},$success:this._success.bind(this),$failure:this._failure.bind(this)})},_success:function(){hui.ui.showMessage({text:"Beskeden er nu sendt",icon:"common/success",duration:2e3}),this.element.reset()},_failure:function(){hui.ui.showMessage({text:"Beskeden kunne desværre ikke afleveres",duration:5e3})}},window.define&&define("op.part.Formula"),op.part.Image=function(e){var t=this.element=hui.get(e.element),i=(t.src,t.parentNode)
i.style.position="relative",i.style.display="block"
var n=hui.build("img",{src:t.src+"&contrast=-20&brightness=80&blur=30",style:"position: absolute; left: 0; top: 0;",parent:i})
hui.animate({node:n,duration:1e3,delay:1e3,ease:hui.ease.flicker,css:{opacity:0}}),hui.listen(n,"mouseover",function(){hui.animate({node:n,duration:500,delay:0,ease:hui.ease.fastSlow,css:{opacity:1}})}),hui.listen(n,"mouseout",function(){hui.animate({node:n,duration:1e3,delay:1e3,ease:hui.ease.flicker,css:{opacity:0}})})},window.define&&define("op.part.Image"),op.part.Poster=function(e){this.options=hui.override({duration:1500,interval:5e3,delay:0},e),this.name=e.name,this.element=hui.get(e.element),this.container=hui.get.firstByClass(this.element,"part_poster_pages"),this.pages=hui.get.byClass(this.element,"part_poster_page"),this.index=0,this.indicators=[],this._buildNavigator(),this.options.editmode||window.setTimeout(this._callNext.bind(this),this.options.delay),hui.listen(this.element,"click",this._onClick.bind(this)),hui.ui.extend(this)},op.part.Poster.prototype={_buildNavigator:function(){this.navigator=hui.build("div",{"class":"part_poster_navigator",parent:this.element})
for(var e=0;e<this.pages.length;e++)this.indicators.push(hui.build("a",{parent:this.navigator,data:e,href:"javascript://","class":0==e?"part_poster_current":""}))},next:function(){var e=this.index+1
e>=this.pages.length&&(e=0),this.goToPage(e)},previous:function(){var e=this.index-1
0>e&&(e=this.pages.length-1),this.goToPage(e)},setPage:function(e){if(!(null===e||void 0===e||e==this.index||this.pages.length-1<e)){this.pages[this.index].style.display="none",this.pages[e].style.display="block",this.index=e
for(var t=0;t<this.indicators.length;t++)hui.cls.set(this.indicators[t],"part_poster_current",t==e)}},goToPage:function(e){if(e!=this.index){window.clearTimeout(this.timer)
var t={container:this.container,duration:this.options.duration}
t.hide={element:this.pages[this.index],effect:"slideLeft"},hui.cls.remove(this.indicators[this.index],"part_poster_current"),this.index=e,t.show={element:this.pages[this.index],effect:"slideRight"},hui.cls.add(this.indicators[this.index],"part_poster_current"),hui.transition(t),this.options.editmode||this._callNext(),this.fire("pageChanged",e)}},_callNext:function(){this.timer=window.setTimeout(this.next.bind(this),this.options.interval)},_onClick:function(e){e=hui.event(e)
var t=e.findByTag("a")
t&&hui.cls.has(t.parentNode,"part_poster_navigator")&&this.goToPage(parseInt(t.getAttribute("data")))}},window.define&&define("op.part.Poster"),op.part.Map=function(e){this.options=hui.override({maptype:"roadmap",zoom:8},e),this.container=hui.get(e.element),hui.ui.onReady(this.initialize.bind(this))},op.part.Map.defered=[],op.part.Map.onReady=function(e){hui.log("onReady... loaded:"+this.loaded),this.loaded?e():this.defered.push(e),void 0===this.loaded&&(this.loaded=!1,window.opMapReady=function(){hui.log("ready")
for(var e=0;e<this.defered.length;e++)this.defered[e]()
window.opMapReady=null,this.loaded=!0}.bind(this),hui.require("https://maps.googleapis.com/maps/api/js?sensor=false&callback=opMapReady"))},op.part.Map.types={roadmap:"ROADMAP",terrain:"TERRAIN"},op.part.Map.prototype={initialize:function(){hui.log("init"),op.part.Map.onReady(this.ready.bind(this))},ready:function(){{var e={zoom:this.options.zoom,center:new google.maps.LatLng(-34.397,150.644),mapTypeId:google.maps.MapTypeId[this.options.type.toUpperCase()],scrollwheel:!1}
this.options.markers}if(this.options.center&&(e.center=new google.maps.LatLng(this.options.center.latitude,this.options.center.longitude)),this.map=new google.maps.Map(this.container,e),this.options.center){var t=new google.maps.Marker({position:new google.maps.LatLng(this.options.center.latitude,this.options.center.longitude),map:this.map,icon:new google.maps.MarkerImage(op.context+"style/basic/gfx/part_map_pin.png",new google.maps.Size(29,30),new google.maps.Point(0,0),new google.maps.Point(8,26))}),i=hui.get.firstByClass(this.element,"part_map_text")
if(i){var n=new google.maps.InfoWindow({content:hui.build("div",{text:i.innerHTML,"class":"part_map_bubble"})})
n.open(this.map,t)}return
var t}}},window.define&&define("op.part.Map"),op.part.Movie=function(e){this.options=e,this.element=hui.get(e.element),this._attach()},op.part.Movie.prototype={_attach:function(){hui.listen(this.element,"click",this._activate.bind(this))
var e=hui.get.firstByClass(this.element,"part_movie_poster")
if(e){var t=e.getAttribute("data-id")
if(t){var i=window.devicePixelRatio||1,n=op.context+"services/images/?id="+t+"&width="+e.clientWidth*i+"&height="+e.clientHeight*i
e.style.backgroundImage="url("+n+")"}else{var o=e.getAttribute("data-vimeo-id")
o&&this._vimeo(o,e)}}},_activate:function(){var e=hui.get.firstByClass(this.element,"part_movie_body"),t=hui.get.firstByTag(this.element,"noscript")
t&&(e.innerHTML=hui.dom.getText(t)),e.style.background=""},_vimeo:function(e,t){var i="callback_"+e,n="http://vimeo.com/api/v2/video/"+e+".json?callback="+i
window[i]=function(e){t.style.backgroundImage="url("+e[0].thumbnail_large+")"}
hui.build("script",{type:"text/javascript",src:n,parent:document.head})}},window.define&&define("op.part.Movie"),hui.transition=function(e){var t=e.hide,i=e.show,n=hui.transition[i.effect],o=hui.transition[t.effect]
hui.style.set(e.container,{height:e.container.clientHeight+"px",position:"relative"}),hui.style.set(t.element,{width:e.container.clientWidth+"px",position:"absolute",boxSizing:"border-box"}),hui.style.set(i.element,{width:e.container.clientWidth+"px",position:"absolute",display:"block",visibility:"hidden",boxSizing:"border-box"}),hui.animate({node:e.container,css:{height:i.element.clientHeight+"px"},duration:e.duration+10,ease:hui.ease.slowFastSlow,onComplete:function(){hui.style.set(e.container,{height:"",position:""})}}),o.beforeHide(t.element),o.hide(t.element,e.duration,function(){hui.style.set(t.element,{display:"none",position:"static",width:""})}),n.beforeShow(i.element),hui.style.set(i.element,{display:"block",visibility:"visible"}),n.show(i.element,e.duration,function(){hui.style.set(i.element,{position:"static",width:""})})},hui.transition.css=function(e){this.options=e},hui.transition.css.prototype={beforeShow:function(e){hui.style.set(e,this.options.hidden)},show:function(e,t,i){hui.animate({node:e,css:this.options.visible,duration:t,ease:hui.ease.slowFastSlow,onComplete:i})},beforeHide:function(e){hui.style.set(e,this.options.visible)},hide:function(e,t,i){hui.animate({node:e,css:this.options.hidden,duration:t,ease:hui.ease.slowFastSlow,onComplete:function(){i(),hui.style.set(e,this.options.visible)}.bind(this)})}},hui.transition.dissolve=new hui.transition.css({visible:{opacity:1},hidden:{opacity:0}}),hui.transition.scale=new hui.transition.css({visible:{opacity:1,transform:"scale(1)"},hidden:{opacity:0,transform:"scale(.9)"}}),hui.transition.slideLeft=new hui.transition.css({visible:{opacity:1,marginLeft:"0%"},hidden:{opacity:0,marginLeft:"-100%"}}),hui.transition.slideRight=new hui.transition.css({visible:{opacity:1,marginLeft:"0%"},hidden:{opacity:0,marginLeft:"100%"}}),op.SearchField=function(e){e=this.options=hui.override({placeholderClass:"placeholder",placeholder:""},e),this.field=hui.get(e.element),this.field.onfocus=function(){this.field.value==e.placeholder?(this.field.value="",hui.cls.add(this.field,e.placeholderClass)):this.field.select()}.bind(this),this.field.onblur=function(){""==this.field.value&&(hui.cls.add(this.field,e.placeholderClass),this.field.value=e.placeholder)}.bind(this),this.field.onblur()},window.define&&define("op.SearchField"),op.Dissolver=function(e){e=this.options=hui.override({wait:4e3,transition:2e3,delay:0},e),this.pos=Math.floor(Math.random()*(e.elements.length-1e-5)),this.z=1,e.elements[this.pos].style.display="block",window.setTimeout(this.next.bind(this),e.wait+e.delay)},op.Dissolver.prototype={next:function(){this.pos++,this.z++
var e=this.options.elements
this.pos==e.length&&(this.pos=0)
var t=e[this.pos]
hui.style.setOpacity(t,0),hui.style.set(t,{display:"block",zIndex:this.z}),hui.animate(t,"opacity",1,this.options.transition,{ease:hui.ease.slowFastSlow,onComplete:function(){window.setTimeout(this.next.bind(this),this.options.wait)}.bind(this)})}},window.define&&define("op.Dissolver"),Poster=function(){this.poster=hui.get("poster"),this.left=hui.get("poster_left"),this.right=hui.get("poster_right"),this.progress=hui.get("poster_loader"),this.context="style/in2isoft/gfx/",this.leftImages=["poster_in2isoft_image.png","poster_publisher_image.png","poster_in2igui_image.png","poster_onlineobjects_image.png"],this.rightImages=["poster_in2isoft_text.png","poster_publisher_text.png","poster_in2igui_text.png","poster_onlineobjects_text.png"],this.leftImages=["poster_humanise_image.png","poster_editor_image.png","poster_hui_image.png","poster_onlineobjects_image.png"],this.rightImages=["poster_humanise_text.png","poster_editor_text.png","poster_hui_text.png","poster_onlineobjects_text.png"],this.links=["om/","produkter/onlinepublisher/","teknologi/in2iGui/","produkter/onlineobjects/"],this.leftPos=-1,this.rightPos=-1
var e=this
this.poster.onclick=function(){document.location=op.page.path+e.links[e.leftPos]},this.preload()},Poster.prototype.start=function(){this.left.scrollLeft=495
var e=this,t=op.page.path+this.context
new hui.animation.Loop([function(){e.leftPos++,e.leftPos>=e.leftImages.length&&(e.leftPos=0),hui.get("poster_left_inner").style.backgroundImage="url('"+t+e.leftImages[e.leftPos]+"')",e.rightPos++,e.rightPos>=e.rightImages.length&&(e.rightPos=0),hui.get("poster_right_inner").style.backgroundImage="url('"+t+e.rightImages[e.rightPos]+"')"},{duration:1e3},{element:this.left,property:"scrollLeft",value:"0",duration:1e3,ease:hui.ease.fastSlow,wait:500},{element:this.right,property:"scrollLeft",value:"495",duration:1e3,ease:hui.ease.fastSlow},{duration:4e3},{element:this.left,property:"scrollLeft",value:"495",duration:1e3,ease:hui.ease.quintIn,wait:500},{element:this.right,property:"scrollLeft",value:"0",duration:1e3,ease:hui.ease.quintIn}]).start()},Poster.prototype.preload=function(){var e=new hui.Preloader({context:op.page.path+this.context})
e.setDelegate({allImagesDidLoad:function(){this.progress.style.display="none",this.start()}.bind(this),imageDidLoad:function(e,t){this.progress.innerHTML=Math.round(e/t*100)+"%"}.bind(this)}),e.addImages(this.leftImages),e.addImages(this.rightImages),e.load()},define("Poster",Poster),require(["hui"],function(){var e=function(e){this.element=e.element,hui.collect(this.nodes,this.element),this._attach()}
e.prototype={nodes:{icon:"layout_search_icon",text:"layout_search_text"},_attach:function(){hui.listen(this.nodes.icon,"click",this._toggle.bind(this)),hui.listen(this.nodes.text,"focus",this._focus.bind(this)),hui.listen(this.nodes.text,"blur",this._blur.bind(this))},_toggle:function(){hui.cls.toggle(document.body,"layout_searching"),window.setTimeout(function(){try{this.nodes.text.focus()}catch(e){}}.bind(this),100)},_focus:function(){hui.cls.add(document.body,"layout_searching")},_blur:function(){hui.cls.remove(document.body,"layout_searching")}},new e({element:hui.find(".layout_search")})})
