if(!op)var op={}
op.preview=!1,op.page=op.page||{id:null,path:null,template:null},op.ignite=function(){if(this.preview||(document.onkeydown=function(e){if(e=hui.event(e),e.returnKey&&e.shiftKey){e.stop()
var i
i=function(e){e=hui.event(e),e.returnKey&&(hui.unListen(document,"keyup",i),hui.browser.msie||op.user.internal?window.location=op.page.path+"Editor/index.php?page="+op.page.id:(e.stop(),op.showLogin()))},hui.listen(document,"keyup",i)}return!0},hui.request({url:op.context+"services/statistics/",parameters:{page:op.page.id,referrer:document.referrer,uri:document.location.href}})),hui.browser.msie7&&hui.onReady(function(){hui.cls.add(document.body.parentNode,"msie7")}),hui.browser.msie7||hui.browser.msie6){for(var e=hui.get.byClass(document.body,"shared_frame"),i=0;i<e.length;i++)e[i].style.width=e[i].clientWidth+"px",e[i].style.display="block"
for(var t=hui.get.byClass(document.body,"document_row"),i=t.length-1;i>=0;i--){var o=t[i].style.cssText,n=10,s=o.match(/border-spacing: ([0-9]+)/m)
s&&(n=s[1])
for(var a=hui.build("table",{"class":t[i].className,style:o,cellSpacing:n}),r=hui.build("tbody",{parent:a}),h=hui.build("tr",{parent:r}),l=hui.get.byClass(t[i],"document_column"),u=0;u<l.length;u++)for(var d=l[u],c=hui.build("td",{"class":d.className,parent:h,style:d.style.cssText});d.firstChild;)c.appendChild(d.firstChild)
t[i].parentNode.insertBefore(a,t[i]),hui.dom.remove(t[i])}}},op.showLogin=function(){if(this.loginBox)this.loginBox.show(),this.loginForm.focus()
else{if(this.loadingLogin)return void hui.log("Aborting, the box is loading")
this.loadingLogin=!0,hui.ui.showMessage({text:{en:"Loading...",da:"Indlæser..."},busy:!0,delay:300}),hui.ui.require(["Formula","Button","TextField"],function(){hui.ui.hideMessage()
var e=this.loginBox=hui.ui.Box.create({width:300,title:{en:"Access control",da:"Adgangskontrol"},modal:!0,absolute:!0,closable:!0,curtainCloses:!0,padding:10})
this.loginBox.addToDocument()
var i=this.loginForm=hui.ui.Formula.create()
i.listen({$submit:function(){if(e.isVisible()){var t=i.getValues()
op.login(t.username,t.password)}}})
var t=i.buildGroup(null,[{type:"TextField",options:{label:{en:"Username",da:"Brugernavn"},key:"username"}},{type:"TextField",options:{label:{en:"Password",da:"Kodeord"},key:"password",secret:!0}}]),o=t.createButtons(),n=hui.ui.Button.create({text:{en:"Forgot password?",da:"Glemt kode?"}})
n.listen({$click:function(){document.location=op.context+"Editor/Authentication.php?forgot=true"}}),o.add(n)
var s=hui.ui.Button.create({text:{en:"Cancel",da:"Annuller"}})
s.listen({$click:function(){i.reset(),e.hide(),document.body.focus()}}),o.add(s),o.add(hui.ui.Button.create({text:{en:"Log in",da:"Log ind"},highlighted:!0,submit:!0})),this.loginBox.add(i),this.loginBox.show(),window.setTimeout(function(){i.focus()},100),this.loadingLogin=!1,op.startListening()
var a=new hui.Preloader({context:hui.ui.context+"hui/icons/"})
a.addImages("common/success24.png"),a.load()}.bind(this))}},op.startListening=function(){hui.listen(window,"keyup",function(e){if(e=hui.event(e),e.escapeKey&&this.loginBox.isVisible()){this.loginBox.hide()
var i=hui.get.firstByTag(document.body,"a")
i&&(i.focus(),i.blur()),document.body.blur()}}.bind(this))},op.login=function(e,i){return hui.isBlank(e)||hui.isBlank(i)?(hui.ui.showMessage({text:{en:"Please fill in both fields",da:"Udfyld venligst begge felter"},duration:3e3}),void this.loginForm.focus()):void hui.ui.request({message:{start:{en:"Logging in...",da:"Logger ind..."},delay:300},url:op.context+"Editor/Services/Core/Authentication.php",parameters:{username:e,password:i},$object:function(e){e.success?(hui.ui.showMessage({text:{en:"You are now logged in",da:"Du er nu logget ind"},icon:"common/success",duration:4e3}),op.igniteEditor()):hui.ui.showMessage({text:{en:"The user was not found",da:"Brugeren blev ikke fundet"},icon:"common/warning",duration:4e3})},$failure:function(){hui.ui.showMessage({text:{en:"An internal error occurred",da:"Der skete en fejl internt i systemet"},icon:"common/warning",duration:4e3})}})},op.igniteEditor=function(){window.location=op.page.path+"Editor/index.php?page="+op.page.id},op.showImage=function(e){this.imageViewer||(this.imageViewer=hui.ui.ImageViewer.create({maxWidth:2e3,maxHeight:2e3,perimeter:40,sizeSnap:10}),this.imageViewer.listen(op.imageViewerDelegate)),this.imageViewer.clearImages(),this.imageViewer.addImage(e),this.imageViewer.show()},op.registerImageViewer=function(e,i){hui.get(e).onclick=function(){return op.showImage(i),!1}},op.imageViewerDelegate={$resolveImageUrl:function(e,i,t){var o=e.width?Math.min(i,e.width):i,n=e.height?Math.min(t,e.height):t
return op.page.path+"services/images/?id="+e.id+"&width="+o+"&height="+n+"&format=jpg&quality=100"}},void 0===op.part&&(op.part={}),op.feedback=function(e){hui.require(op.page.path+"style/basic/js/Feedback.js",function(){op.feedback.Controller.init(e)})},window.define&&define("op"),op.part.Formula=function(e){this.element=hui.get(e.element),this.id=e.id,this.inputs=e.inputs,hui.listen(this.element,"submit",this._send.bind(this))},op.part.Formula.prototype={_send:function(e){hui.stop(e)
for(var i=[],t=0;t<this.inputs.length;t++){var o=this.inputs[t],n=hui.get(o.id),s=o.validation
if(s.required&&hui.isBlank(n.value))return hui.ui.showMessage({text:s.message,duration:2e3}),void n.focus()
if("email"==s.syntax&&!hui.isBlank(n.value)){var a=/^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\\n".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA\n-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/
if(!a.test(n.value))return hui.ui.showMessage({text:s.message,duration:2e3}),void n.focus()}i.push({label:o.label,value:n.value})}var r=op.page.path+"services/parts/formula/",h={id:this.id,fields:i}
hui.ui.showMessage({text:"Sender besked...",busy:!0}),hui.ui.request({url:r,json:{data:h},$success:this._success.bind(this),$failure:this._failure.bind(this)})},_success:function(){hui.ui.showMessage({text:"Beskeden er nu sendt",icon:"common/success",duration:2e3}),this.element.reset()},_failure:function(){hui.ui.showMessage({text:"Beskeden kunne desværre ikke afleveres",duration:5e3})}},window.define&&define("op.part.Formula"),op.part.Image=function(e){var i=this.element=hui.get(e.element),t=(i.src,i.parentNode)
t.style.position="relative",t.style.display="block"
var o=hui.build("img",{src:i.src+"&contrast=-20&brightness=80&blur=30",style:"position: absolute; left: 0; top: 0;",parent:t})
hui.animate({node:o,duration:1e3,delay:1e3,ease:hui.ease.flicker,css:{opacity:0}}),hui.listen(o,"mouseover",function(){hui.animate({node:o,duration:500,delay:0,ease:hui.ease.fastSlow,css:{opacity:1}})}),hui.listen(o,"mouseout",function(){hui.animate({node:o,duration:1e3,delay:1e3,ease:hui.ease.flicker,css:{opacity:0}})})},window.define&&define("op.part.Image"),op.part.Poster=function(e){this.options=hui.override({duration:1500,interval:5e3,delay:0},e),this.name=e.name,this.element=hui.get(e.element),this.container=hui.get.firstByClass(this.element,"part_poster_pages"),this.pages=hui.get.byClass(this.element,"part_poster_page"),this.index=0,this.indicators=[],this._buildNavigator(),this.options.editmode||window.setTimeout(this._callNext.bind(this),this.options.delay),hui.listen(this.element,"click",this._onClick.bind(this)),hui.ui.extend(this)},op.part.Poster.prototype={_buildNavigator:function(){this.navigator=hui.build("div",{"class":"part_poster_navigator",parent:this.element})
for(var e=0;e<this.pages.length;e++)this.indicators.push(hui.build("a",{parent:this.navigator,data:e,href:"javascript://","class":0==e?"part_poster_current":""}))},next:function(){var e=this.index+1
e>=this.pages.length&&(e=0),this.goToPage(e)},previous:function(){var e=this.index-1
0>e&&(e=this.pages.length-1),this.goToPage(e)},setPage:function(e){if(!(null===e||void 0===e||e==this.index||this.pages.length-1<e)){this.pages[this.index].style.display="none",this.pages[e].style.display="block",this.index=e
for(var i=0;i<this.indicators.length;i++)hui.cls.set(this.indicators[i],"part_poster_current",i==e)}},goToPage:function(e){if(e!=this.index){window.clearTimeout(this.timer)
var i={container:this.container,duration:this.options.duration}
i.hide={element:this.pages[this.index],effect:"slideLeft"},hui.cls.remove(this.indicators[this.index],"part_poster_current"),this.index=e,i.show={element:this.pages[this.index],effect:"slideRight"},hui.cls.add(this.indicators[this.index],"part_poster_current"),hui.transition(i),this.options.editmode||this._callNext(),this.fire("pageChanged",e)}},_callNext:function(){this.timer=window.setTimeout(this.next.bind(this),this.options.interval)},_onClick:function(e){e=hui.event(e)
var i=e.findByTag("a")
i&&hui.cls.has(i.parentNode,"part_poster_navigator")&&this.goToPage(parseInt(i.getAttribute("data")))}},window.define&&define("op.part.Poster"),op.part.Map=function(e){this.options=hui.override({maptype:"roadmap",zoom:8},e),this.container=hui.get(e.element),hui.ui.onReady(this.initialize.bind(this))},op.part.Map.defered=[],op.part.Map.onReady=function(e){hui.log("onReady... loaded:"+this.loaded),this.loaded?e():this.defered.push(e),void 0===this.loaded&&(this.loaded=!1,window.opMapReady=function(){hui.log("ready")
for(var e=0;e<this.defered.length;e++)this.defered[e]()
window.opMapReady=null,this.loaded=!0}.bind(this),hui.require("https://maps.googleapis.com/maps/api/js?sensor=false&callback=opMapReady"))},op.part.Map.types={roadmap:"ROADMAP",terrain:"TERRAIN"},op.part.Map.prototype={initialize:function(){hui.log("init"),op.part.Map.onReady(this.ready.bind(this))},ready:function(){{var e={zoom:this.options.zoom,center:new google.maps.LatLng(-34.397,150.644),mapTypeId:google.maps.MapTypeId[this.options.type.toUpperCase()],scrollwheel:!1}
this.options.markers}if(this.options.center&&(e.center=new google.maps.LatLng(this.options.center.latitude,this.options.center.longitude)),this.map=new google.maps.Map(this.container,e),this.options.center){var i=new google.maps.Marker({position:new google.maps.LatLng(this.options.center.latitude,this.options.center.longitude),map:this.map,icon:new google.maps.MarkerImage(op.context+"style/basic/gfx/part_map_pin.png",new google.maps.Size(29,30),new google.maps.Point(0,0),new google.maps.Point(8,26))}),t=hui.get.firstByClass(this.element,"part_map_text")
if(t){var o=new google.maps.InfoWindow({content:hui.build("div",{text:t.innerHTML,"class":"part_map_bubble"})})
o.open(this.map,i)}return
var i}}},window.define&&define("op.part.Map"),op.part.Movie=function(e){this.options=e,this.element=hui.get(e.element),this._attach()},op.part.Movie.prototype={_attach:function(){hui.listen(this.element,"click",this._activate.bind(this))
var e=hui.get.firstByClass(this.element,"part_movie_poster")
if(e){var i=e.getAttribute("data-id")
if(i)window.setTimeout(function(){var t=window.devicePixelRatio||1,o=op.context+"services/images/?id="+i+"&width="+e.clientWidth*t+"&height="+e.clientHeight*t
e.style.backgroundImage="url("+o+")"},500)
else{var t=e.getAttribute("data-vimeo-id")
t&&this._vimeo(t,e)}}},_activate:function(){var e=hui.get.firstByClass(this.element,"part_movie_body"),i=hui.get.firstByTag(this.element,"noscript")
i&&(e.innerHTML=hui.dom.getText(i)),e.style.background=""},_vimeo:function(e,i){var t="callback_"+e,o="http://vimeo.com/api/v2/video/"+e+".json?callback="+t
window[t]=function(e){i.style.backgroundImage="url("+e[0].thumbnail_large+")"}
hui.build("script",{type:"text/javascript",src:o,parent:document.head})}},window.define&&define("op.part.Movie"),hui.transition=function(e){var i=e.hide,t=e.show,o=hui.transition[t.effect],n=hui.transition[i.effect]
hui.style.set(e.container,{height:e.container.clientHeight+"px",position:"relative"}),hui.style.set(i.element,{width:e.container.clientWidth+"px",position:"absolute",boxSizing:"border-box"}),hui.style.set(t.element,{width:e.container.clientWidth+"px",position:"absolute",display:"block",visibility:"hidden",boxSizing:"border-box"}),hui.animate({node:e.container,css:{height:t.element.clientHeight+"px"},duration:e.duration+10,ease:hui.ease.slowFastSlow,onComplete:function(){hui.style.set(e.container,{height:"",position:""})}}),n.beforeHide(i.element),n.hide(i.element,e.duration,function(){hui.style.set(i.element,{display:"none",position:"static",width:""})}),o.beforeShow(t.element),hui.style.set(t.element,{display:"block",visibility:"visible"}),o.show(t.element,e.duration,function(){hui.style.set(t.element,{position:"static",width:""})})},hui.transition.css=function(e){this.options=e},hui.transition.css.prototype={beforeShow:function(e){hui.style.set(e,this.options.hidden)},show:function(e,i,t){hui.animate({node:e,css:this.options.visible,duration:i,ease:hui.ease.slowFastSlow,onComplete:t})},beforeHide:function(e){hui.style.set(e,this.options.visible)},hide:function(e,i,t){hui.animate({node:e,css:this.options.hidden,duration:i,ease:hui.ease.slowFastSlow,onComplete:function(){t(),hui.style.set(e,this.options.visible)}.bind(this)})}},hui.transition.dissolve=new hui.transition.css({visible:{opacity:1},hidden:{opacity:0}}),hui.transition.scale=new hui.transition.css({visible:{opacity:1,transform:"scale(1)"},hidden:{opacity:0,transform:"scale(.9)"}}),hui.transition.slideLeft=new hui.transition.css({visible:{opacity:1,marginLeft:"0%"},hidden:{opacity:0,marginLeft:"-100%"}}),hui.transition.slideRight=new hui.transition.css({visible:{opacity:1,marginLeft:"0%"},hidden:{opacity:0,marginLeft:"100%"}}),op.SearchField=function(e){e=this.options=hui.override({placeholderClass:"placeholder",placeholder:""},e),this.field=hui.get(e.element),this.field.onfocus=function(){this.field.value==e.placeholder?(this.field.value="",hui.cls.add(this.field,e.placeholderClass)):this.field.select()}.bind(this),this.field.onblur=function(){""==this.field.value&&(hui.cls.add(this.field,e.placeholderClass),this.field.value=e.placeholder)}.bind(this),this.field.onblur()},window.define&&define("op.SearchField"),op.Dissolver=function(e){e=this.options=hui.override({wait:4e3,transition:2e3,delay:0},e),this.pos=Math.floor(Math.random()*(e.elements.length-1e-5)),this.z=1,e.elements[this.pos].style.display="block",window.setTimeout(this.next.bind(this),e.wait+e.delay)},op.Dissolver.prototype={next:function(){this.pos++,this.z++
var e=this.options.elements
this.pos==e.length&&(this.pos=0)
var i=e[this.pos]
hui.style.setOpacity(i,0),hui.style.set(i,{display:"block",zIndex:this.z}),hui.animate(i,"opacity",1,this.options.transition,{ease:hui.ease.slowFastSlow,onComplete:function(){window.setTimeout(this.next.bind(this),this.options.wait)}.bind(this)})}},window.define&&define("op.Dissolver")
var ctrl={attach:function(){var e=hui.find("nav"),i={"/":"top","/cv/":"about","":"theater","/fotografier/":"photos","/kommunikation/":"communication","/film/":"movies","/en/":"top","/en/cv/":"about","":"theater","/en/photos/":"photos","/en/communication-training/":"communication","/en/movie-clips/":"movies"}
hui.listen(e,"click",function(e){e=hui.event(e)
var t=e.findByTag("a")
if(t){var o=i[t.getAttribute("data-path")]
if(!o)return
for(var n=hui.get.byTag(document.body,"a"),s=0;s<n.length;s++)if(o==n[s].getAttribute("name"))return e.stop(),void hui.window.scrollTo({element:n[s].parentNode,duration:1e3,top:"theater"==o?40:140})}}),hui.listen("handmade","click",function(e){hui.stop(e)
var i=hui.get("humanise")
i.style.display="block",window.setTimeout(function(){hui.cls.add(i,"visible")})})
var t=hui.find(".theater"),o=hui.find(".theater_photo",t),n=hui.find(".theater_stages",t),s=hui.window.getViewWidth()
if(hui.browser.animation||(hui.style.setOpacity(o,0),hui.style.setOpacity(n,0)),t){var a=!1
hui.parallax.listen({element:t,$scroll:function(e){var i=e>.2&&.8>e&&s>700
a!=i&&(hui.cls.set(document.body,"is-full",i),hui.browser.animation?hui.cls.set(document.body,"is-dark",i):hui.animate({node:document.body,css:{"background-color":i?"#000":"#fff"},duration:1e3}),a=i)
var r=e>.3&&.7>e
this.shown!=r&&(r&&hui.animate({node:o,css:{opacity:r?1:0},ease:hui.ease.flicker,duration:3e3,$complete:function(){hui.browser.animation?hui.cls.set(t,"is-final",e>0&&1>e):hui.animate({node:n,css:{opacity:r?1:0},ease:hui.ease.slowFast,duration:5e3})}}),this.shown=r)}}),hui.parallax.listen({$resize:function(e,i){t.style.height=e>700?Math.round(.8*i)+"px":"",hui.browser.mediaQueries||hui.cls.set(document.body,"small",1200>e),s=e}})}}}
hui.onReady(ctrl.attach.bind(ctrl)),require(["hui"],function(e){var i=function(i){this.element=i.element,this.key=this.element.getAttribute("data-video"),e.listen(this.element,"click",this._click.bind(this))}
i.prototype={_click:function(){this._moveTop(),i.active&&i.active.disable()
var t="http://www.youtube.com/embed/"+this.key,o='<iframe class="movies_iframe" width="640" height="480" src="'+t+'?autoplay=1" frameborder="0" allowfullscreen="allowfullscreen"></iframe>'
e.build("div",{"class":"movies_player",html:o,parent:this.element}),i.active=this},_moveTop:function(){var i=this.element.parentNode,t=i.parentNode,o=e.find(".movies_item",t)
o!=i&&(t.removeChild(o),t.insertBefore(o,i),t.removeChild(i),o=e.find(".movies_item",t),t.insertBefore(i,o))},disable:function(){var i=e.find(".movies_player",this.element)
e.dom.remove(i)}}
for(var t=e.get.byClass(document.body,"js-movie-poster"),o=0;o<t.length;o++)new i({element:t[o]})}),require(["hui"],function(e){var i=function(e){return(2*e-1)*(2*e-1)*-1+1}
e.onReady(function(){var t=e.get.byClass(document.body,"js-photo")
e.each(t,function(t){var o=e.find(".js-photo-effect",t),n=e.position.get(t),s={width:t.clientWidth,height:t.clientHeight}
e.ui.listen({$$afterResize:function(){n=e.position.get(t),s={width:t.clientWidth,height:t.clientHeight}}}),e.listen(window,"mousemove",function(t){t=e.event(t)
var a=(t.getLeft()-n.left)/s.width,r=(t.getTop()-n.top)/s.height
o.style.marginLeft=20*a+"px",o.style.marginTop=20*r+"px"
var h=e.between(0,i(a),1)*e.between(0,i(r),1)
o.style.opacity=h})})})})
